//! Type alias for SM4 in CBC mode (NIST SP 800-38A Sec 6.2; draft-ribose-cfrg-sm4-10 Sec 8.4),
//! with padding.
//!
//! `bouncycastle-modes` is deliberately cipher-agnostic, so `Cbc` takes the permutation, the
//! direction, and the `KEY_LEN` / `BLOCK_LEN` const parameters, and `bouncycastle-padding`'s
//! adapters take five more. This alias pins all of them except the two choices a caller actually
//! makes: the direction and the padding scheme. It adds nothing to the engine: the permutation
//! still implements none of the data-encryption traits itself (see the crate docs), the mode does.
//!
//! ```text
//! SM4_CBC<Encrypting, PKCS7>
//! SM4_CBC<Decrypting, NoPadding>
//! ```
//!
//! CBC is defined only on whole blocks (SP 800-38A Sec 5.2), so CBC on data of any other length is
//! always CBC *plus a padding scheme*, and the scheme changes the ciphertext and must be agreed by
//! both ends. Naming it in the type makes that choice explicit and makes a mismatched pair a
//! compile error. The block-aligned API -- whole blocks in place, length checked at compile time --
//! is `bouncycastle_modes::Cbc` itself, which this wraps. See
//! [`PaddedMode`](bouncycastle_padding::PaddedMode) for how one alias covers both directions.

use crate::{BLOCK_LEN, KEY_LEN, SM4};
use bouncycastle_modes::{Cbc, Decrypting, Encrypting};
use bouncycastle_padding::PaddedMode;

// Imports needed for docs
#[allow(unused_imports)]
use bouncycastle_core::traits::{SimpleCipherDecryptor, SimpleCipherEncryptor};
#[allow(unused_imports)]
use bouncycastle_padding::{NoPadding, PKCS7};
// end of imports needed for docs

/// SM4 in CBC mode with a padding scheme.
///
/// `Dir` is [`Encrypting`] or [`Decrypting`] and `Pad` is [`PKCS7`] or [`NoPadding`]; the wrong
/// direction is a compile error, not a runtime check. The IV is generated by encryption and
/// returned; it is never supplied.
///
/// ```
/// use bouncycastle_sm4::SM4_CBC;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{SimpleCipherDecryptor, SimpleCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
/// use bouncycastle_padding::PKCS7;
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey)
///     .expect("a 16-byte symmetric cipher key");
/// let message = b"a message of no particular length";
///
/// let (iv, ciphertext) =
///     SM4_CBC::<Encrypting, PKCS7>::encrypt(&key, message).expect("encryption");
/// let recovered =
///     SM4_CBC::<Decrypting, PKCS7>::decrypt(&key, &iv, &ciphertext).expect("decryption");
/// assert_eq!(recovered, message);
/// ```
///
/// With [`NoPadding`] nothing is added, and a message that is not a whole number of blocks is an
/// error rather than something silently padded:
///
/// ```
/// use bouncycastle_sm4::SM4_CBC;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::SimpleCipherEncryptor;
/// use bouncycastle_modes::Encrypting;
/// use bouncycastle_padding::NoPadding;
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey).unwrap();
///
/// let mut out = [0u8; 16];
/// let (_iv, written) = SM4_CBC::<Encrypting, NoPadding>::encrypt_out(&key, &[0u8; 16], &mut out)
///     .expect("a whole block is fine");
/// assert_eq!(written, 16);
///
/// let mut out = [0u8; 16];
/// assert!(SM4_CBC::<Encrypting, NoPadding>::encrypt_out(&key, b"hello", &mut out).is_err());
/// ```
#[allow(non_camel_case_types)]
pub type SM4_CBC<Dir, Pad> = <Dir as PaddedMode<
    Cbc<SM4, Encrypting, KEY_LEN, BLOCK_LEN>,
    Cbc<SM4, Decrypting, KEY_LEN, BLOCK_LEN>,
    Pad,
    KEY_LEN,
    BLOCK_LEN,
    BLOCK_LEN,
>>::Mode;
