//! Type alias for SM4 in CBC mode (NIST SP 800-38A Sec 6.2; draft-ribose-cfrg-sm4-10 Sec 8.4).
//!
//! `bouncycastle-modes` is deliberately cipher-agnostic, so `Cbc` takes the permutation, the
//! direction, and the `KEY_LEN` / `BLOCK_LEN` const parameters. This alias pins the SM4 values so
//! callers never spell them out. It adds nothing to the engine: the permutation still implements
//! none of the data-encryption traits itself (see the crate docs), the mode does.

use crate::{BLOCK_LEN, KEY_LEN, SM4};
use bouncycastle_modes::Cbc;

/// SM4 in CBC mode. `Dir` is [`bouncycastle_modes::Encrypting`] or
/// [`bouncycastle_modes::Decrypting`]; the wrong direction is a compile error, not a runtime check.
///
/// The IV is generated by encryption and returned; it is never supplied. Encryption and decryption
/// work in place.
///
/// ```
/// use bouncycastle_sm4::SM4_CBC;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{BlockCipherDecryptor, BlockCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey)
///     .expect("a 16-byte symmetric cipher key");
/// // 48 bytes: three whole blocks. The length is checked at compile time.
/// let message = [0u8; 48];
/// let mut data = message;
/// let iv = SM4_CBC::<Encrypting>::encrypt(&key, &mut data).unwrap();
/// assert_ne!(data, message);
/// SM4_CBC::<Decrypting>::decrypt(&key, &iv, &mut data).unwrap();
/// assert_eq!(data, message);
///
/// // Streaming, a few blocks at a time:
/// let (mut enc, iv) = SM4_CBC::<Encrypting>::do_encrypt_init(&key).unwrap();
/// let mut first = [0u8; 16];
/// let mut rest = [1u8; 32];
/// enc.do_encrypt(&mut first).unwrap();
/// enc.do_encrypt(&mut rest).unwrap();
/// let mut dec = SM4_CBC::<Decrypting>::do_decrypt_init(&key, &iv).unwrap();
/// dec.do_decrypt(&mut first).unwrap();
/// dec.do_decrypt(&mut rest).unwrap();
/// assert_eq!(first, [0u8; 16]);
/// assert_eq!(rest, [1u8; 32]);
/// ```
///
/// A length that is not a whole number of blocks is a **compile** error, not a runtime one:
///
/// ```compile_fail
/// use bouncycastle_sm4::SM4_CBC;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::BlockCipherEncryptor;
/// use bouncycastle_modes::Encrypting;
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey).unwrap();
/// // 47 bytes is not a multiple of 16: the inline const assertion in `encrypt` fails to compile.
/// let _ = SM4_CBC::<Encrypting>::encrypt(&key, &mut [0u8; 47]);
/// ```
#[allow(non_camel_case_types)]
pub type SM4_CBC<Dir> = Cbc<SM4, Dir, KEY_LEN, BLOCK_LEN>;
