//! Type alias for SM4 in CFB mode (draft-ribose-cfrg-sm4-10 Sec 8.5; NIST SP 800-38A Sec 6.3),
//! full-block segment.
//!
//! `bouncycastle-modes` is deliberately cipher-agnostic, so `Cfb` takes the permutation, the
//! direction, and the `KEY_LEN` / `BLOCK_LEN` const parameters. This alias pins the SM4 values so
//! callers never spell them out. It adds nothing to the engine: the permutation still implements
//! none of the data-encryption traits itself (see the crate docs), the mode does.
//!
//! The segment size is the full block, so this is the draft's **SM4-CFB-128**, one of the four
//! variants Sec 8.5.1 names: "SM4-CFB-1 ... SM4-CFB-8 ... SM4-CFB-64 ... SM4-CFB-128, the 128-bit
//! SM4-CFB mode, where s is set to 128." The `s = 8` variant is a different, non-interoperable mode
//! with its own alias, [`SM4_CFB8`](crate::SM4_CFB8); `s = 1` and `s = 64` are not implemented.
//!
//! Sec 8.5 says the plaintext "must be a multiple of the block size". `Cfb` accepts any length and
//! treats a short tail as a final segment of `s = 8r`, which is what every streaming CFB128
//! implementation does; see "The final partial segment" in the `bouncycastle_modes::Cfb` docs for
//! why that is well defined. On whole blocks -- the only lengths the draft's Appendix A.2.4 vectors
//! cover -- the two readings coincide.

use crate::{BLOCK_LEN, KEY_LEN, SM4};
use bouncycastle_modes::Cfb;

/// SM4 in CFB128 mode. `Dir` is [`bouncycastle_modes::Encrypting`] or
/// [`bouncycastle_modes::Decrypting`]; the wrong direction is a compile error, not a runtime check.
///
/// CFB is a stream cipher, so the data is a `&mut [u8]` of any length and the ciphertext is exactly
/// as long as the plaintext. The IV is one 16-byte block, generated by encryption and returned; it
/// is never supplied. Encryption and decryption work in place.
///
/// ```
/// use bouncycastle_sm4::SM4_CFB;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{StreamCipherDecryptor, StreamCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey)
///     .expect("a 16-byte symmetric cipher key");
/// // 47 bytes: a stream cipher does not need a whole number of blocks.
/// let message = [0u8; 47];
/// let mut data = message;
/// let (_, iv) = SM4_CFB::<Encrypting>::encrypt(&key, &mut data).unwrap();
/// assert_ne!(data, message);
/// SM4_CFB::<Decrypting>::decrypt(&key, &iv, &mut data).unwrap();
/// assert_eq!(data, message);
///
/// // Streaming, at any byte boundary:
/// let (mut enc, iv) = SM4_CFB::<Encrypting>::do_encrypt_init(&key).unwrap();
/// let mut first = [0u8; 5];
/// let mut rest = [1u8; 30];
/// enc.do_encrypt(&mut first).unwrap();
/// enc.do_encrypt(&mut rest).unwrap();
/// let mut dec = SM4_CFB::<Decrypting>::do_decrypt_init(&key, &iv).unwrap();
/// dec.do_decrypt(&mut first).unwrap();
/// dec.do_decrypt(&mut rest).unwrap();
/// assert_eq!(first, [0u8; 5]);
/// assert_eq!(rest, [1u8; 30]);
/// ```
#[allow(non_camel_case_types)]
pub type SM4_CFB<Dir> = Cfb<SM4, Dir, KEY_LEN, BLOCK_LEN>;
