//! Type alias for SM4 in CFB8 mode (draft-ribose-cfrg-sm4-10 Sec 8.5 with `s = 8`; NIST
//! SP 800-38A Sec 6.3, `s = 8`).
//!
//! `bouncycastle-modes` is deliberately cipher-agnostic, so `Cfb8` takes the permutation, the
//! direction, and the `KEY_LEN` / `BLOCK_LEN` const parameters. This alias pins the SM4 values so
//! callers never spell them out. It adds nothing to the engine: the permutation still implements
//! none of the data-encryption traits itself (see the crate docs), the mode does.
//!
//! This is the draft's **SM4-CFB-8**, named in Sec 8.5.1 as "the 8-bit SM4-CFB mode, where s is set
//! to 8". It is a **different, non-interoperable mode** from SM4-CFB-128, not a variant of it:
//! their ciphertexts differ from the second byte, and it costs a full SM4 call per byte, sixteen
//! times the work of [`SM4_CFB`](crate::SM4_CFB). See the `bouncycastle_modes::Cfb8` docs for when
//! that is the right trade.
//!
//! The draft defines the mode but publishes no example for it -- Appendix A.2.4's vectors are all
//! `s = 128` -- so `tests/stream_mode_tests.rs` pins this alias against the Sec 8.5.2 equations
//! evaluated directly over the permutation instead.

use crate::{BLOCK_LEN, KEY_LEN, SM4};
use bouncycastle_modes::Cfb8;

/// SM4 in CFB8 mode. `Dir` is [`bouncycastle_modes::Encrypting`] or
/// [`bouncycastle_modes::Decrypting`]; the wrong direction is a compile error, not a runtime check.
///
/// CFB8 is a stream cipher with a one-byte segment, so the data is a `&mut [u8]` of any length and
/// the ciphertext is exactly as long as the plaintext. The IV is one 16-byte block, generated by
/// encryption and returned; it is never supplied. Encryption and decryption work in place.
///
/// ```
/// use bouncycastle_sm4::{SM4_CFB, SM4_CFB8};
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{StreamCipherDecryptor, StreamCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey)
///     .expect("a 16-byte symmetric cipher key");
/// // 5 bytes: CFB8's segment is one byte, so any length at all is fine.
/// let message = *b"hello";
/// let mut data = message;
/// let (_, iv) = SM4_CFB8::<Encrypting>::encrypt(&key, &mut data).unwrap();
/// assert_ne!(data, message);
/// SM4_CFB8::<Decrypting>::decrypt(&key, &iv, &mut data).unwrap();
/// assert_eq!(data, message);
///
/// // Streaming, at any byte boundary:
/// let (mut enc, iv) = SM4_CFB8::<Encrypting>::do_encrypt_init(&key).unwrap();
/// let mut first = [0u8; 3];
/// let mut rest = [1u8; 20];
/// enc.do_encrypt(&mut first).unwrap();
/// enc.do_encrypt(&mut rest).unwrap();
/// let mut dec = SM4_CFB8::<Decrypting>::do_decrypt_init(&key, &iv).unwrap();
/// dec.do_decrypt(&mut first).unwrap();
/// dec.do_decrypt(&mut rest).unwrap();
/// assert_eq!(first, [0u8; 3]);
/// assert_eq!(rest, [1u8; 20]);
///
/// // SM4-CFB-8 and SM4-CFB-128 are not interchangeable: same key, same IV, different ciphertext.
/// let mut as_cfb8 = message;
/// let (_, iv) = SM4_CFB8::<Encrypting>::encrypt(&key, &mut as_cfb8).unwrap();
/// let mut as_cfb128 = as_cfb8;
/// SM4_CFB::<Decrypting>::decrypt(&key, &iv, &mut as_cfb128).unwrap();
/// assert_ne!(as_cfb128, message);
/// ```
#[allow(non_camel_case_types)]
pub type SM4_CFB8<Dir> = Cfb8<SM4, Dir, KEY_LEN, BLOCK_LEN>;
