//! Type alias for SM4 in CTR mode (draft-ribose-cfrg-sm4-10 Sec 8.7; NIST SP 800-38A Sec 6.5).
//!
//! `bouncycastle-modes` is deliberately cipher-agnostic, so `Ctr` takes the permutation, the
//! direction, and the `KEY_LEN` / `BLOCK_LEN` / `INIT_DATA_LEN` const parameters. This alias pins
//! the SM4 values so callers never spell them out. It adds nothing to the engine: the permutation
//! still implements none of the data-encryption traits itself (see the crate docs), the mode does.
//!
//! # The nonce length is 12, so the counter is 4
//!
//! `Ctr` splits the counter block into a nonce and a counter by the length of its init data, and
//! this alias chooses a **12-byte nonce**, leaving the 4-byte counter that is the mode's maximum.
//! That allows 2^32 blocks -- 64 GiB -- in one message, and past it the mode errors rather than
//! repeating keystream. A shorter message limit in exchange for more nonce bits is available by
//! naming `Ctr` directly with a 13, 14 or 15-byte nonce.
//!
//! Sec 8.7 takes the counter sequence `T` as an input beside the nonce and requires only that "the
//! counter could be any sequence that does not repeat within the block size", so `nonce || counter`
//! is one admissible choice rather than a deviation; SP 800-38A Appendix B.2, which `Ctr`
//! implements, is the same construction spelled out. The draft's own Appendix A.2.5 examples take a
//! different one -- the whole 16-byte IV is `T_1` and the block is incremented as a unit -- which
//! this split cannot express, so those vectors drive a reference CTR over the permutation in
//! `tests/stream_mode_tests.rs` and this alias is checked against that reference.

use crate::{BLOCK_LEN, KEY_LEN, SM4};
use bouncycastle_modes::Ctr;

/// The nonce length this alias uses, leaving a 4-byte counter.
pub const CTR_NONCE_LEN: usize = 12;

/// SM4 in CTR mode with a 12-byte nonce. `Dir` is [`bouncycastle_modes::Encrypting`] or
/// [`bouncycastle_modes::Decrypting`]; the wrong direction is a compile error, not a runtime check.
///
/// CTR is a stream cipher, so the data is a `&mut [u8]` of any length and the ciphertext is exactly
/// as long as the plaintext. The nonce is generated by encryption and returned; it is never
/// supplied. Encryption and decryption work in place, and are the same operation.
///
/// ```
/// use bouncycastle_sm4::SM4_CTR;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{StreamCipherDecryptor, StreamCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey)
///     .expect("a 16-byte symmetric cipher key");
/// // 47 bytes: a stream cipher does not need a whole number of blocks.
/// let message = [0u8; 47];
/// let mut data = message;
/// let (_, nonce) = SM4_CTR::<Encrypting>::encrypt(&key, &mut data).unwrap();
/// assert_eq!(nonce.len(), 12);
/// assert_ne!(data, message);
/// SM4_CTR::<Decrypting>::decrypt(&key, &nonce, &mut data).unwrap();
/// assert_eq!(data, message);
///
/// // Streaming, at any byte boundary:
/// let (mut enc, nonce) = SM4_CTR::<Encrypting>::do_encrypt_init(&key).unwrap();
/// let mut first = [0u8; 5];
/// let mut rest = [1u8; 30];
/// enc.do_encrypt(&mut first).unwrap();
/// enc.do_encrypt(&mut rest).unwrap();
/// let mut dec = SM4_CTR::<Decrypting>::do_decrypt_init(&key, &nonce).unwrap();
/// dec.do_decrypt(&mut first).unwrap();
/// dec.do_decrypt(&mut rest).unwrap();
/// assert_eq!(first, [0u8; 5]);
/// assert_eq!(rest, [1u8; 30]);
/// ```
#[allow(non_camel_case_types)]
pub type SM4_CTR<Dir> = Ctr<SM4, Dir, KEY_LEN, BLOCK_LEN, CTR_NONCE_LEN>;
