[package]
name = "bouncycastle-core-test-framework"
version.workspace = true
edition.workspace = true

# core-test-framework only needs to build for std environments
# However it must appropriately enable or disable `std` feature
# for all dependencies
[features]
default = ["std"]
std = [
    "bouncycastle-core/std",
]

[dependencies]
bouncycastle-core = { workspace = true, default-features = false }

[dev-dependencies]
