use bouncycastle_core_interface::traits::Hash;
use crate::MLDSA44PublicKey;

/// Note that the PH expected here *is not the same* as the `mu` computed by [compute_mu] ... blah blah explain.
struct DummyForTheCommentToCompile {}

/// Note: yes, a HashMLDSAPublicKey is just a re-branded MLDSAPublicKey because they are structurally
/// the same, but we are giving them different types to indicate that they _should_ not be used interchangeably
/// in order to prevent certain cross-protocol attacks where a verifier is tricked into accepting an
/// ML-DSA signature that was actually generated by the HashML-DSA algorithm, and vice-versa.
/// IE a given key should be used ONLY for ML-DSA or HashML-DSA and should not be used sometimes for one and sometimes for the other.
/// We won't prevent you from doing so; for example you can convert between them by encoding the key to bytes and
/// back into the other type, but we want to make you aware that you're opening yourself up to cross-protocol attacks.
pub type HashMLDSA44PublicKey = MLDSA44PublicKey;

/// An instance of the HashML-DSA algorithm.
///
/// We are exposing the HashMLDSA struct this way so that alternative hash functions can be used
/// without requiring modification of this source code; you can add your own hash function
/// by specifying the hash function to use (in the verifier), and specifying the bytes of the OID to
/// to use as its domain separator in constructing the message representative M'.
// todo: put an example of this in the unit tests and then copy that example into these ducs
// todo: figure out how to do a const str param
pub struct HashMLDSA<HASH: Hash + Default, const oid_name: [u8]> {
    _phantom: std::marker::PhantomData<HASH>,
}
