//! Type aliases for AES in CBC mode (NIST SP 800-38A Sec 6.2), with padding.
//!
//! `bouncycastle-modes` is deliberately cipher-agnostic, so `Cbc` takes the permutation, the
//! direction, and the `KEY_LEN` / `BLOCK_LEN` const parameters, and `bouncycastle-padding`'s
//! adapters take five more. These aliases pin all of them except the two choices a caller actually
//! makes: the direction and the padding scheme. They add nothing to the engine -- the permutation
//! still implements none of the data-encryption traits itself (see the crate docs), the mode does.
//!
//! ```text
//! AES_CBC_128<Encrypting, PKCS7>   // AES-128, CBC, PKCS#7 padded, encrypting
//! AES_CBC_256<Decrypting, NoPadding>
//! ```
//!
//! # Why the padding is part of the alias
//!
//! CBC is defined only on whole blocks (SP 800-38A Sec 5.2), and the recommendation puts the
//! formatting of anything else outside its scope (Appendix A). So CBC on real data is always CBC
//! *plus a padding scheme*, and the scheme is not an implementation detail: it changes the
//! ciphertext, and both ends must agree on it. Naming it in the type makes that choice explicit at
//! every use, and makes a mismatched pair a compile error rather than a decryption that returns
//! plausible-looking rubbish.
//!
//! The two schemes `bouncycastle-padding` provides are [`PKCS7`], which is what almost everyone
//! means by "padded CBC" (RFC 5652 s. 6.3), and [`NoPadding`], which adds nothing and instead
//! *rejects* a message that is not a whole number of blocks -- useful for formats already defined
//! on block boundaries, where silently padding would be wrong.
//!
//! # These are the arbitrary-length API
//!
//! A padded alias implements [`SymmetricCipherEncryptor`] / [`SymmetricCipherDecryptor`], not the
//! block traits: `encrypt_out` / `decrypt_out` and the streaming `do_update_out` / `do_final`, all
//! taking a `&[u8]` of any length. The block-aligned API, with its compile-time length checks and
//! its in-place data methods, is `bouncycastle_modes::Cbc` itself, which these wrap:
//!
//! ```text
//! bouncycastle_modes::Cbc<Aes128, Encrypting, 16, 16>   // block-aligned, in place
//! AES_CBC_128<Encrypting, PKCS7>                        // any length, padded
//! ```
//!
//! # How one alias covers both directions
//!
//! `PaddedEncryptor` and `PaddedDecryptor` are two distinct types, so a plain type alias cannot
//! select between them on a `Dir` parameter. [`PaddedMode`] does it instead: it is implemented for
//! each direction marker and projects to the right adapter, and the aliases are written as that
//! projection. The only visible consequence is that `Dir` must be
//! [`Encrypting`](bouncycastle_modes::Encrypting) or
//! [`Decrypting`](bouncycastle_modes::Decrypting), which was already true.

use crate::padded_mode::PaddedMode;
use crate::{Aes128, Aes192, Aes256, BLOCK_LEN};
use bouncycastle_modes::{Cbc, Decrypting, Encrypting};

// Imports needed for docs
#[allow(unused_imports)]
use bouncycastle_core::traits::{SymmetricCipherDecryptor, SymmetricCipherEncryptor};
#[allow(unused_imports)]
use bouncycastle_padding::{NoPadding, PKCS7, PaddedDecryptor, PaddedEncryptor};
// end of imports needed for docs

/// AES-128 in CBC mode with a padding scheme.
///
/// `Dir` is [`Encrypting`] or [`Decrypting`] and `Pad` is [`PKCS7`] or [`NoPadding`]; the wrong
/// direction is a compile error, not a runtime check. The IV is generated by encryption and
/// returned; it is never supplied.
///
/// ```
/// use bouncycastle_aes::AES_CBC_128;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{SymmetricCipherDecryptor, SymmetricCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
/// use bouncycastle_padding::PKCS7;
///
/// type Enc = AES_CBC_128<Encrypting, PKCS7>;
/// type Dec = AES_CBC_128<Decrypting, PKCS7>;
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey)
///     .expect("a 16-byte symmetric cipher key");
///
/// // 5 bytes: PKCS#7 pads it to one block, so the padding does the work CBC cannot.
/// let message = b"hello";
/// let mut ciphertext = [0u8; 16];
/// let (iv, written) = Enc::encrypt_out(&key, message, &mut ciphertext).expect("encryption");
/// assert_eq!(written, 16);
///
/// let mut plaintext = [0u8; 16];
/// let n = Dec::decrypt_out(&key, &iv, &ciphertext, &mut plaintext).expect("decryption");
/// assert_eq!(&plaintext[..n], message);
/// ```
///
/// With [`NoPadding`] nothing is added, and a message that is not a whole number of blocks is an
/// error at `do_final` rather than something silently padded:
///
/// ```
/// use bouncycastle_aes::AES_CBC_128;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::SymmetricCipherEncryptor;
/// use bouncycastle_modes::Encrypting;
/// use bouncycastle_padding::NoPadding;
///
/// type Enc = AES_CBC_128<Encrypting, NoPadding>;
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey).unwrap();
///
/// // A whole block is fine, and comes out the same length.
/// let mut out = [0u8; 16];
/// let (_iv, written) = Enc::encrypt_out(&key, &[0u8; 16], &mut out).expect("aligned");
/// assert_eq!(written, 16);
///
/// // Five bytes is not, and is refused rather than padded.
/// let mut out = [0u8; 16];
/// assert!(Enc::encrypt_out(&key, b"hello", &mut out).is_err());
/// ```
///
/// The padding scheme is part of the type, so the two schemes are different types and cannot be
/// interchanged. A value built with one will not satisfy a binding annotated with the other:
///
/// ```compile_fail
/// use bouncycastle_aes::AES_CBC_128;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::SymmetricCipherEncryptor;
/// use bouncycastle_modes::Encrypting;
/// use bouncycastle_padding::{NoPadding, PKCS7};
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey).unwrap();
///
/// // Built as NoPadding, annotated as PKCS7: mismatched types.
/// let (enc, _iv) = AES_CBC_128::<Encrypting, NoPadding>::do_encrypt_init(&key).unwrap();
/// let _mismatched: AES_CBC_128<Encrypting, PKCS7> = enc;
/// ```
///
/// The same code with the annotation corrected does compile, which is what makes the failure above
/// meaningful rather than incidental:
///
/// ```
/// use bouncycastle_aes::AES_CBC_128;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::SymmetricCipherEncryptor;
/// use bouncycastle_modes::Encrypting;
/// use bouncycastle_padding::NoPadding;
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey).unwrap();
///
/// let (enc, _iv) = AES_CBC_128::<Encrypting, NoPadding>::do_encrypt_init(&key).unwrap();
/// let _matched: AES_CBC_128<Encrypting, NoPadding> = enc;
/// ```
#[allow(non_camel_case_types)]
pub type AES_CBC_128<Dir, Pad> = <Dir as PaddedMode<
    Cbc<Aes128, Encrypting, 16, BLOCK_LEN>,
    Cbc<Aes128, Decrypting, 16, BLOCK_LEN>,
    Pad,
    16,
    BLOCK_LEN,
>>::Mode;

/// AES-192 in CBC mode with a padding scheme. See [`AES_CBC_128`].
///
/// ```
/// use bouncycastle_aes::AES_CBC_192;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{SymmetricCipherDecryptor, SymmetricCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
/// use bouncycastle_padding::PKCS7;
///
/// let key = KeyMaterial::<24>::from_bytes_as_type(&[0x42; 24], KeyType::SymmetricCipherKey).unwrap();
/// let message = b"a message of no particular length";
///
/// let (iv, ciphertext) =
///     AES_CBC_192::<Encrypting, PKCS7>::encrypt(&key, message).expect("encryption");
/// let recovered =
///     AES_CBC_192::<Decrypting, PKCS7>::decrypt(&key, &iv, &ciphertext).expect("decryption");
/// assert_eq!(recovered, message);
/// ```
#[allow(non_camel_case_types)]
pub type AES_CBC_192<Dir, Pad> = <Dir as PaddedMode<
    Cbc<Aes192, Encrypting, 24, BLOCK_LEN>,
    Cbc<Aes192, Decrypting, 24, BLOCK_LEN>,
    Pad,
    24,
    BLOCK_LEN,
>>::Mode;

/// AES-256 in CBC mode with a padding scheme. See [`AES_CBC_128`].
///
/// ```
/// use bouncycastle_aes::AES_CBC_256;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{SymmetricCipherDecryptor, SymmetricCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
/// use bouncycastle_padding::PKCS7;
///
/// let key = KeyMaterial::<32>::from_bytes_as_type(&[0x42; 32], KeyType::SymmetricCipherKey).unwrap();
/// let message = b"another message";
///
/// let (iv, ciphertext) =
///     AES_CBC_256::<Encrypting, PKCS7>::encrypt(&key, message).expect("encryption");
/// let recovered =
///     AES_CBC_256::<Decrypting, PKCS7>::decrypt(&key, &iv, &ciphertext).expect("decryption");
/// assert_eq!(recovered, message);
/// ```
#[allow(non_camel_case_types)]
pub type AES_CBC_256<Dir, Pad> = <Dir as PaddedMode<
    Cbc<Aes256, Encrypting, 32, BLOCK_LEN>,
    Cbc<Aes256, Decrypting, 32, BLOCK_LEN>,
    Pad,
    32,
    BLOCK_LEN,
>>::Mode;
