//! Type aliases for AES in CFB8 mode (NIST SP 800-38A Sec 6.3, `s = 8`).
//!
//! `bouncycastle-modes` is deliberately cipher-agnostic, so `Cfb8` takes the permutation, the
//! direction, and the `KEY_LEN` / `BLOCK_LEN` const parameters. These aliases pin the AES values so
//! callers never spell them out. They add nothing to the engine: the permutation still implements
//! none of the data-encryption traits itself (see the crate docs), the mode does.
//!
//! CFB8 is a **different, non-interoperable mode** from CFB128, not a variant of it: their
//! ciphertexts differ from the second byte, and it costs a full AES call per byte, sixteen times
//! the work of [`AES_CFB_128`](crate::AES_CFB_128). See the `bouncycastle_modes::Cfb8` docs for
//! when that is the right trade.

use crate::{Aes128, Aes192, Aes256, BLOCK_LEN};
use bouncycastle_modes::Cfb8;

/// AES-128 in CFB8 mode. `Dir` is [`bouncycastle_modes::Encrypting`] or
/// [`bouncycastle_modes::Decrypting`]; the wrong direction is a compile error, not a runtime check.
///
/// CFB8 is a stream cipher with a one-byte segment, so the data is a `&mut [u8]` of any length and
/// the ciphertext is exactly as long as the plaintext. The IV is generated by encryption and
/// returned; it is never supplied. Encryption and decryption work in place.
///
/// ```
/// use bouncycastle_aes::{AES_CFB8_128, AES_CFB_128};
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{StreamCipherDecryptor, StreamCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey)
///     .expect("a 16-byte symmetric cipher key");
/// // 5 bytes: CFB8's segment is one byte, so any length at all is fine.
/// let message = *b"hello";
/// let mut data = message;
/// let iv = AES_CFB8_128::<Encrypting>::encrypt(&key, &mut data).unwrap();
/// assert_ne!(data, message);
/// AES_CFB8_128::<Decrypting>::decrypt(&key, &iv, &mut data).unwrap();
/// assert_eq!(data, message);
///
/// // Streaming, at any byte boundary:
/// let (mut enc, iv) = AES_CFB8_128::<Encrypting>::do_encrypt_init(&key).unwrap();
/// let mut first = [0u8; 3];
/// let mut rest = [1u8; 20];
/// enc.do_encrypt(&mut first).unwrap();
/// enc.do_encrypt(&mut rest).unwrap();
/// let mut dec = AES_CFB8_128::<Decrypting>::do_decrypt_init(&key, &iv).unwrap();
/// dec.do_decrypt(&mut first).unwrap();
/// dec.do_decrypt(&mut rest).unwrap();
/// assert_eq!(first, [0u8; 3]);
/// assert_eq!(rest, [1u8; 20]);
///
/// // CFB8 and CFB128 are not interchangeable: same key, same IV, different ciphertext.
/// let mut as_cfb8 = message;
/// let iv = AES_CFB8_128::<Encrypting>::encrypt(&key, &mut as_cfb8).unwrap();
/// let mut as_cfb128 = as_cfb8;
/// AES_CFB_128::<Decrypting>::decrypt(&key, &iv, &mut as_cfb128).unwrap();
/// assert_ne!(as_cfb128, message);
/// ```
#[allow(non_camel_case_types)]
pub type AES_CFB8_128<Dir> = Cfb8<Aes128, Dir, 16, BLOCK_LEN>;

/// AES-192 in CFB8 mode. See [`AES_CFB8_128`].
///
/// ```
/// use bouncycastle_aes::AES_CFB8_192;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{StreamCipherDecryptor, StreamCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<24>::from_bytes_as_type(&[0x42; 24], KeyType::SymmetricCipherKey).unwrap();
/// let mut data = [0u8; 30];
/// let iv = AES_CFB8_192::<Encrypting>::encrypt(&key, &mut data).unwrap();
/// AES_CFB8_192::<Decrypting>::decrypt(&key, &iv, &mut data).unwrap();
/// assert_eq!(data, [0u8; 30]);
/// ```
#[allow(non_camel_case_types)]
pub type AES_CFB8_192<Dir> = Cfb8<Aes192, Dir, 24, BLOCK_LEN>;

/// AES-256 in CFB8 mode. See [`AES_CFB8_128`].
///
/// ```
/// use bouncycastle_aes::AES_CFB8_256;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{StreamCipherDecryptor, StreamCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<32>::from_bytes_as_type(&[0x42; 32], KeyType::SymmetricCipherKey).unwrap();
/// let mut data = [0u8; 30];
/// let iv = AES_CFB8_256::<Encrypting>::encrypt(&key, &mut data).unwrap();
/// AES_CFB8_256::<Decrypting>::decrypt(&key, &iv, &mut data).unwrap();
/// assert_eq!(data, [0u8; 30]);
/// ```
#[allow(non_camel_case_types)]
pub type AES_CFB8_256<Dir> = Cfb8<Aes256, Dir, 32, BLOCK_LEN>;
