//! Type aliases for AES in GCM (NIST SP 800-38D).
//!
//! See [`bouncycastle_cipher::modes::gcm`] for details on the abstract Galois/Counter Mode construction.
//!
//! The aliases here are authenticated ciphers: encryption produces a tag as well as a ciphertext,
//! and decryption either returns the plaintext or fails the tag check. Both directions implement
//! [`AEADCipherEncryptor`] / [`AEADCipherDecryptor`], which keep the tag detached, and
//! [`SymmetricCipherEncryptor`] / [`SymmetricCipherDecryptor`], which carry it inline as
//! `ciphertext || tag`. The nonce is generated by encryption and returned; there is no API for
//! supplying one. `Dir` is [`Encrypting`] or [`Decrypting`]; the wrong direction is a compile
//! error, not a runtime check.
//!
//! The tag is fixed at 128 bits, the maximum SP 800-38D Sec 5.2.1.2 allows. For a shorter tag
//! (96, 104, 112 or 120 bits), name [`Gcm`] directly with the desired `TAG_LEN`. The nonce is
//! always [`GCM_NONCE_LEN`] (12 bytes / 96 bits): `Gcm` has no nonce-length parameter at all,
//! unlike `Ctr`'s aliases, because SP 800-38D's `len(IV) != 96` branch (deriving `J0` from a GHASH
//! of the IV) is not implemented.
//!
//! # Usage Examples
//!
//! ## One-shot API
//!
//! Basic usage can be obtained via the [`AEADCipherEncryptor`] and [`AEADCipherDecryptor`] API,
//! which returns the tag separately from the ciphertext:
//!
//! ```
//! use bouncycastle_aes::{AES_GCM_256, AES_GCM_256_Key};
//! use bouncycastle_core::traits::{AEADCipherDecryptor, AEADCipherEncryptor, SymmetricCipherKey};
//! use bouncycastle_cipher::{Decrypting, Encrypting};
//!
//! // Define ourselves convenience types.
//! type AESEnc = AES_GCM_256<Encrypting>;
//! type AESDec = AES_GCM_256<Decrypting>;
//!
//! let key = AES_GCM_256_Key::new_from_os().expect("a fresh key");
//!
//! // The associated data is authenticated but not encrypted; the message is both.
//! let aad = b"header, sent in the clear";
//! let message = b"a message of no particular length";
//!
//! // The nonce is generated for you and returned; there is no API for supplying one.
//! let (nonce, ciphertext, tag) = AESEnc::encrypt_detached(&key, aad, message).expect("encryption");
//! assert_eq!(ciphertext.len(), message.len(), "GCM never expands the payload");
//!
//! let recovered = AESDec::decrypt_detached(&key, &nonce, aad, &ciphertext, &tag).expect("decryption");
//! assert_eq!(recovered, message);
//!
//! // Tampering with the ciphertext, the tag or the associated data fails the tag check.
//! let mut tampered = ciphertext.clone();
//! tampered[0] ^= 1;
//! assert!(AESDec::decrypt_detached(&key, &nonce, aad, &tampered, &tag).is_err());
//! assert!(AESDec::decrypt_detached(&key, &nonce, b"other header", &ciphertext, &tag).is_err());
//! ```
//!
//! ## Inline `ciphertext || tag`
//!
//! Through the [`SymmetricCipherEncryptor`] and [`SymmetricCipherDecryptor`] API the tag is
//! appended to the ciphertext, so the output is 16 bytes longer than the input:
//!
//! ```
//! use bouncycastle_aes::{AES_GCM_128, AES_GCM_128_Key};
//! use bouncycastle_core::traits::{SymmetricCipherDecryptor, SymmetricCipherEncryptor, SymmetricCipherKey};
//! use bouncycastle_cipher::{Decrypting, Encrypting};
//!
//! // Define ourselves convenience types.
//! type AESEnc = AES_GCM_128<Encrypting>;
//! type AESDec = AES_GCM_128<Decrypting>;
//!
//! let key = AES_GCM_128_Key::new_from_os().expect("a fresh key");
//! let message = b"a message of no particular length at all";
//!
//! let mut ciphertext = vec![0u8; AESEnc::encrypt_out_len(message.len())];
//! let (nonce, written) = AESEnc::encrypt_out(&key, message, &mut ciphertext).expect("encryption");
//! assert_eq!(written, message.len() + 16, "the ciphertext plus the tag");
//!
//! let mut plaintext = vec![0u8; AESDec::decrypt_out_len(ciphertext.len())];
//! let n = AESDec::decrypt_out(&key, &nonce, &ciphertext, &mut plaintext).expect("decryption");
//! assert_eq!(&plaintext[..n], message);
//! ```
//!
//! ## Streaming API
//!
//! For data that arrives in pieces, the following APIs can be used. All associated data must be
//! given via `do_update_aad` before the first piece of data, and the tag comes from
//! `do_encrypt_final`:
//!
//! ```
//! use bouncycastle_aes::{AES_GCM_128, AES_GCM_128_Key};
//! use bouncycastle_core::traits::{
//!     AEADCipherDecryptor, AEADCipherEncryptor, SymmetricCipherDecryptor, SymmetricCipherEncryptor,
//!     SymmetricCipherKey,
//! };
//! use bouncycastle_cipher::{Decrypting, Encrypting};
//!
//! // Define ourselves convenience types.
//! type AESEnc = AES_GCM_128<Encrypting>;
//! type AESDec = AES_GCM_128<Decrypting>;
//!
//! let key = AES_GCM_128_Key::new_from_os().expect("a fresh key");
//! let aad = b"header";
//! let plaintext = [0x5Au8; 50];
//!
//! // Encrypt in 7-byte pieces. A piece is encrypted as soon as it is given, so each call writes
//! // exactly as many bytes as it was handed.
//! let (mut encryptor, nonce) = AESEnc::do_encrypt_init(&key).expect("encrypt init");
//! encryptor.do_update_aad(aad).expect("aad");
//! let mut ciphertext = Vec::new();
//! for piece in plaintext.chunks(7) {
//!     let mut out = [0u8; 7];
//!     let bytes_written = encryptor.do_encrypt_out(piece, &mut out).expect("encryption");
//!     ciphertext.extend_from_slice(&out[..bytes_written]);
//! }
//! // The tag is computed over everything, so it is the last thing out.
//! let (tag, tag_len) = encryptor.do_encrypt_final().expect("the tag");
//! ciphertext.extend_from_slice(&tag[..tag_len]);
//! assert_eq!(ciphertext.len(), plaintext.len() + 16);
//!
//! // Decrypt in 19-byte pieces. The decryptor holds back the last 16 bytes it has seen, since
//! // those may be the tag, so a call can write fewer bytes than it was handed; `do_decrypt_final`
//! // checks the tag and releases whatever is still held back.
//! let mut decryptor = AESDec::do_decrypt_init(&key, &nonce).expect("decrypt init");
//! decryptor.do_update_aad(aad).expect("aad");
//! let mut recovered = Vec::new();
//! for piece in ciphertext.chunks(19) {
//!     let mut out = [0u8; 19];
//!     let bytes_written = decryptor.do_decrypt_out(piece, &mut out).expect("decryption");
//!     recovered.extend_from_slice(&out[..bytes_written]);
//! }
//! let (last, last_len) = decryptor.do_decrypt_final().expect("a valid tag");
//! recovered.extend_from_slice(&last[..last_len]);
//! assert_eq!(recovered, plaintext);
//! ```
//!
//! # 🚨 Security Considerations 🚨
//!
//! All security considerations from [`bouncycastle_cipher::modes::gcm`] apply.

use crate::hazmat::{AES128Internal, AES192Internal, AES256Internal};
use bouncycastle_cipher::modes::Gcm;

use bouncycastle_core::errors::{KeyMaterialError, RNGError};
use bouncycastle_core::key_material::{KeyMaterial, KeyMaterialTrait, KeyType};
use bouncycastle_core::security_strength::SecurityStrength;
use bouncycastle_core::traits::SymmetricCipherKey;
use bouncycastle_rng::{HashDRBG_SHA256, HashDRBG_SHA512};
// Imports needed for docs
#[allow(unused_imports)]
use bouncycastle_cipher::modes::GCM_NONCE_LEN;
#[allow(unused_imports)]
use bouncycastle_cipher::{Decrypting, Encrypting};
#[allow(unused_imports)]
use bouncycastle_core::traits::{
    AEADCipherDecryptor, AEADCipherEncryptor, SymmetricCipherDecryptor, SymmetricCipherEncryptor,
};
// end of imports needed for docs

/// AES-128 in GCM with a 128-bit tag.
#[allow(non_camel_case_types)]
pub type AES_GCM_128<Dir> = Gcm<AES128Internal, Dir, AES_GCM_128_Key, 16, 16>;

/// An AES-GCM-128 key.
#[derive(Clone, PartialEq, Eq)]
#[allow(non_camel_case_types)]
pub struct AES_GCM_128_Key(KeyMaterial<16>);

impl SymmetricCipherKey<16> for AES_GCM_128_Key {
    fn from_keymaterial(key: KeyMaterial<16>) -> Result<Self, KeyMaterialError> {
        if key.key_type() != KeyType::SymmetricCipherKey {
            return Err(KeyMaterialError::InvalidKeyType("Must be SymmetricCipherKey"));
        }
        if key.security_strength() < SecurityStrength::_128bit {
            return Err(KeyMaterialError::InvalidKeyType(
                "Key's Security strength must be at least 128bit",
            ));
        }
        Ok(Self(key))
    }

    fn get_key(&self) -> &KeyMaterial<16> {
        &self.0
    }

    fn new_from_os() -> Result<Self, RNGError> {
        Self::new_from_rng(&mut HashDRBG_SHA256::new_from_os())
    }
}

/// AES-192 in GCM with a 128-bit tag.
#[allow(non_camel_case_types)]
pub type AES_GCM_192<Dir> = Gcm<AES192Internal, Dir, AES_GCM_192_Key, 24, 16>;

/// An AES-GCM-192 key.
#[derive(Clone, PartialEq, Eq)]
#[allow(non_camel_case_types)]
pub struct AES_GCM_192_Key(KeyMaterial<24>);

impl SymmetricCipherKey<24> for AES_GCM_192_Key {
    fn from_keymaterial(key: KeyMaterial<24>) -> Result<Self, KeyMaterialError> {
        if key.key_type() != KeyType::SymmetricCipherKey {
            return Err(KeyMaterialError::InvalidKeyType("Must be SymmetricCipherKey"));
        }
        if key.security_strength() < SecurityStrength::_192bit {
            return Err(KeyMaterialError::InvalidKeyType(
                "Key's Security strength must be at least 192bit",
            ));
        }
        Ok(Self(key))
    }

    fn get_key(&self) -> &KeyMaterial<24> {
        &self.0
    }

    fn new_from_os() -> Result<Self, RNGError> {
        Self::new_from_rng(&mut HashDRBG_SHA512::new_from_os())
    }
}

/// AES-256 in GCM with a 128-bit tag. See [`AES_GCM_128`].
#[allow(non_camel_case_types)]
pub type AES_GCM_256<Dir> = Gcm<AES256Internal, Dir, AES_GCM_256_Key, 32, 16>;

/// An AES-GCM-256 key.
#[derive(Clone, PartialEq, Eq)]
#[allow(non_camel_case_types)]
pub struct AES_GCM_256_Key(KeyMaterial<32>);

impl SymmetricCipherKey<32> for AES_GCM_256_Key {
    fn from_keymaterial(key: KeyMaterial<32>) -> Result<Self, KeyMaterialError> {
        if key.key_type() != KeyType::SymmetricCipherKey {
            return Err(KeyMaterialError::InvalidKeyType("Must be SymmetricCipherKey"));
        }
        if key.security_strength() < SecurityStrength::_256bit {
            return Err(KeyMaterialError::InvalidKeyType(
                "Key's Security strength must be at least 256bit",
            ));
        }
        Ok(Self(key))
    }

    fn get_key(&self) -> &KeyMaterial<32> {
        &self.0
    }

    fn new_from_os() -> Result<Self, RNGError> {
        Self::new_from_rng(&mut HashDRBG_SHA512::new_from_os())
    }
}
