//! Type aliases for AES in GCM (NIST SP 800-38D).
//!
//! `bouncycastle-modes` is deliberately cipher-agnostic, so `Gcm` takes the permutation, the
//! direction, and the `KEY_LEN` / `TAG_LEN` const parameters. These aliases pin the AES values and
//! fix the tag length at 128 bits, the maximum SP 800-38D Sec 5.2.1.2 allows. For a shorter tag
//! (96, 104, 112 or 120 bits), name `bouncycastle_modes::Gcm` directly with the desired `TAG_LEN`.
//!
//! The nonce is always [`bouncycastle_modes::GCM_NONCE_LEN`] (12 bytes / 96 bits): `Gcm` has no
//! nonce-length parameter at all, unlike `Ctr`'s aliases, because SP 800-38D's `len(IV) != 96`
//! branch (deriving `J0` from a GHASH of the IV) is not implemented -- see the `gcm` module docs in
//! `bouncycastle-modes`.

use crate::{AES_128, AES_192, AES_256};
use bouncycastle_modes::Gcm;

/// AES-128 in GCM with a 128-bit tag. `Dir` is [`bouncycastle_modes::Encrypting`] or
/// [`bouncycastle_modes::Decrypting`]; the wrong direction is a compile error, not a runtime check.
///
/// The nonce is generated by the encryptor and returned; it is never supplied. Both directions
/// implement [`AEADCipherEncryptor`](bouncycastle_core::traits::AEADCipherEncryptor) /
/// [`AEADCipherDecryptor`](bouncycastle_core::traits::AEADCipherDecryptor); see the `gcm` module
/// docs in `bouncycastle-modes` for the detached-tag and inline `ciphertext || tag` layouts, and for
/// the security considerations (nonce uniqueness above all).
///
/// ```
/// use bouncycastle_aes::AES_GCM_128;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{AEADCipherDecryptor, AEADCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey)
///     .expect("a 16-byte symmetric cipher key");
/// let aad = b"header, sent in the clear";
/// let message = *b"attack at dawn!!";
///
/// // Detached tag, one-shot.
/// let mut ciphertext = [0u8; 16];
/// let (nonce, _, tag) =
///     AES_GCM_128::<Encrypting>::encrypt_out_detached(&key, aad, &message, &mut ciphertext).unwrap();
/// let mut plaintext = [0u8; 16];
/// AES_GCM_128::<Decrypting>::decrypt_out_detached(&key, &nonce, aad, &ciphertext, &tag, &mut plaintext)
///     .unwrap();
/// assert_eq!(plaintext, message);
/// ```
///
/// Inline `ciphertext || tag`, through [`SymmetricCipherEncryptor`](bouncycastle_core::traits::SymmetricCipherEncryptor) / [`SymmetricCipherDecryptor`](bouncycastle_core::traits::SymmetricCipherDecryptor):
///
/// ```
/// use bouncycastle_aes::AES_GCM_128;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{SymmetricCipherDecryptor, SymmetricCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey).unwrap();
/// let aad = b"associated data";
/// let message = b"a message of no particular length at all";
///
/// let mut ciphertext = vec![0u8; AES_GCM_128::<Encrypting>::encrypt_out_len(message.len())];
/// let (nonce, written) =
///     AES_GCM_128::<Encrypting>::encrypt_out(&key, message, &mut ciphertext).unwrap();
/// assert_eq!(written, ciphertext.len());
///
/// let mut plaintext = vec![0u8; AES_GCM_128::<Decrypting>::decrypt_out_max_len(ciphertext.len())];
/// let n = AES_GCM_128::<Decrypting>::decrypt_out(&key, &nonce, &ciphertext, &mut plaintext).unwrap();
/// assert_eq!(&plaintext[..n], &message[..]);
/// ```
///
/// Streaming, with AAD fed via `do_update_aad` before any data:
///
/// ```
/// use bouncycastle_aes::AES_GCM_128;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{
///     AEADCipherDecryptor, AEADCipherEncryptor, SymmetricCipherDecryptor, SymmetricCipherEncryptor,
/// };
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x99; 16], KeyType::SymmetricCipherKey).unwrap();
/// let (mut enc, nonce) = AES_GCM_128::<Encrypting>::do_encrypt_init(&key).unwrap();
/// enc.do_update_aad(b"header").unwrap();
/// let mut ct = [0u8; 5];
/// enc.do_update_out(b"hello", &mut ct).unwrap();
/// let (tag, tag_len) = enc.do_final().unwrap();
///
/// let mut dec = AES_GCM_128::<Decrypting>::do_decrypt_init(&key, &nonce).unwrap();
/// dec.do_update_aad(b"header").unwrap();
/// let mut full_ct = ct.to_vec();
/// full_ct.extend_from_slice(&tag[..tag_len]);
/// let mut pt = vec![0u8; full_ct.len()];
/// let n = dec.do_update_out(&full_ct, &mut pt).unwrap();
/// let (_last, last_len) = dec.do_final().unwrap();
/// assert_eq!(&pt[..n + last_len], b"hello");
/// ```
#[allow(non_camel_case_types)]
pub type AES_GCM_128<Dir> = Gcm<AES_128, Dir, 16, 16>;

/// AES-192 in GCM with a 128-bit tag. See [`AES_GCM_128`].
///
/// ```
/// use bouncycastle_aes::AES_GCM_192;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{AEADCipherDecryptor, AEADCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<24>::from_bytes_as_type(&[0x24; 24], KeyType::SymmetricCipherKey).unwrap();
/// let message = b"a 192-bit key message!!";
/// let (nonce, ciphertext, tag) =
///     AES_GCM_192::<Encrypting>::encrypt_detached(&key, b"aad", message).unwrap();
/// let plaintext =
///     AES_GCM_192::<Decrypting>::decrypt_detached(&key, &nonce, b"aad", &ciphertext, &tag).unwrap();
/// assert_eq!(&plaintext, message);
/// ```
#[allow(non_camel_case_types)]
pub type AES_GCM_192<Dir> = Gcm<AES_192, Dir, 24, 16>;

/// AES-256 in GCM with a 128-bit tag. See [`AES_GCM_128`].
///
/// ```
/// use bouncycastle_aes::AES_GCM_256;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{AEADCipherDecryptor, AEADCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<32>::from_bytes_as_type(&[0x32; 32], KeyType::SymmetricCipherKey).unwrap();
/// let message = b"a 256-bit key message!!";
/// let (nonce, ciphertext, tag) =
///     AES_GCM_256::<Encrypting>::encrypt_detached(&key, b"aad", message).unwrap();
/// let plaintext =
///     AES_GCM_256::<Decrypting>::decrypt_detached(&key, &nonce, b"aad", &ciphertext, &tag).unwrap();
/// assert_eq!(&plaintext, message);
/// ```
#[allow(non_camel_case_types)]
pub type AES_GCM_256<Dir> = Gcm<AES_256, Dir, 32, 16>;
