[package]
name = "ascon"
version = "0.0.0"
edition.workspace = true

[dependencies]
arrayref = "0.3"
bouncycastle-core.workspace = true
bouncycastle-rng.workspace = true
bouncycastle-utils.workspace = true

[dev-dependencies]
bouncycastle-core-test-framework.workspace = true
bouncycastle-hex.workspace = true
bouncycastle-rng.workspace = true
criterion.workspace = true