[package]
name = "bouncycastle-sha2"
version = "0.1.2"
edition.workspace = true

[features]
# Opt-in hardware SHA-256 compression via core::arch. Currently it uses runtime
# SHA-2 detection
asm = []

[dependencies]
bouncycastle-core.workspace = true
bouncycastle-utils.workspace = true

[dev-dependencies]
criterion.workspace = true
bouncycastle-core-test-framework.workspace = true
bouncycastle-rng.workspace = true

[[bench]]
name = "sha2_benches"
harness = false
