//! Type aliases for AES in CBC mode (NIST SP 800-38A Sec 6.2).
//!
//! `bouncycastle-modes` is deliberately cipher-agnostic, so `Cbc` takes the permutation, the
//! direction, and the `KEY_LEN` / `BLOCK_LEN` const parameters. These aliases pin the AES values so
//! callers never spell them out. They add nothing to the engine: the permutation still implements
//! none of the data-encryption traits itself (see the crate docs), the mode does.

use crate::{Aes128, Aes192, Aes256, BLOCK_LEN};
use bouncycastle_modes::Cbc;

/// AES-128 in CBC mode. `Dir` is [`bouncycastle_modes::Encrypting`] or
/// [`bouncycastle_modes::Decrypting`]; the wrong direction is a compile error, not a runtime check.
///
/// The IV is generated by encryption and returned alongside the ciphertext; it is never supplied.
///
/// ```
/// use bouncycastle_aes_lowmemory::AES_CBC_128;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{BlockCipherDecryptor, BlockCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey)
///     .expect("a 16-byte symmetric cipher key");
/// // 48 bytes: three whole blocks. The length is checked at compile time.
/// let message = [0u8; 48];
/// let (iv, ciphertext) = AES_CBC_128::<Encrypting>::encrypt(&key, &message).unwrap();
/// assert_eq!(AES_CBC_128::<Decrypting>::decrypt(&key, &iv, &ciphertext).unwrap(), message);
///
/// // Streaming, a few blocks at a time:
/// let (mut enc, iv) = AES_CBC_128::<Encrypting>::do_encrypt_init(&key).unwrap();
/// let first = enc.do_encrypt(&[0u8; 16]).unwrap();
/// let rest = enc.do_encrypt(&[1u8; 32]).unwrap();
/// let mut dec = AES_CBC_128::<Decrypting>::do_decrypt_init(&key, &iv).unwrap();
/// assert_eq!(dec.do_decrypt(&first).unwrap(), [0u8; 16]);
/// assert_eq!(dec.do_decrypt(&rest).unwrap(), [1u8; 32]);
/// ```
///
/// A length that is not a whole number of blocks is a **compile** error, not a runtime one:
///
/// ```compile_fail
/// use bouncycastle_aes_lowmemory::AES_CBC_128;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::BlockCipherEncryptor;
/// use bouncycastle_modes::Encrypting;
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey).unwrap();
/// // 47 bytes is not a multiple of 16: the inline const assertion in `encrypt` fails to compile.
/// let _ = AES_CBC_128::<Encrypting>::encrypt(&key, &[0u8; 47]);
/// ```
#[allow(non_camel_case_types)]
pub type AES_CBC_128<Dir> = Cbc<Aes128, Dir, 16, BLOCK_LEN>;

/// AES-192 in CBC mode. See [`AES_CBC_128`].
///
/// ```
/// use bouncycastle_aes_lowmemory::AES_CBC_192;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{BlockCipherDecryptor, BlockCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<24>::from_bytes_as_type(&[0x42; 24], KeyType::SymmetricCipherKey).unwrap();
/// let (iv, ct) = AES_CBC_192::<Encrypting>::encrypt(&key, &[0u8; 32]).unwrap();
/// assert_eq!(AES_CBC_192::<Decrypting>::decrypt(&key, &iv, &ct).unwrap(), [0u8; 32]);
/// ```
#[allow(non_camel_case_types)]
pub type AES_CBC_192<Dir> = Cbc<Aes192, Dir, 24, BLOCK_LEN>;

/// AES-256 in CBC mode. See [`AES_CBC_128`].
///
/// ```
/// use bouncycastle_aes_lowmemory::AES_CBC_256;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{BlockCipherDecryptor, BlockCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<32>::from_bytes_as_type(&[0x42; 32], KeyType::SymmetricCipherKey).unwrap();
/// let (iv, ct) = AES_CBC_256::<Encrypting>::encrypt(&key, &[0u8; 32]).unwrap();
/// assert_eq!(AES_CBC_256::<Decrypting>::decrypt(&key, &iv, &ct).unwrap(), [0u8; 32]);
/// ```
#[allow(non_camel_case_types)]
pub type AES_CBC_256<Dir> = Cbc<Aes256, Dir, 32, BLOCK_LEN>;
