//! Type aliases for AES in CBC mode (NIST SP 800-38A Sec 6.2).
//!
//! `bouncycastle-modes` is deliberately cipher-agnostic, so `Cbc` takes the permutation, the
//! direction, and the `KEY_LEN` / `BLOCK_LEN` const parameters. These aliases pin the AES values so
//! callers never spell them out. They add nothing to the engine: the permutation still implements
//! none of the data-encryption traits itself (see the crate docs), the mode does.

use crate::{Aes128, Aes192, Aes256, BLOCK_LEN};
use bouncycastle_modes::Cbc;

/// AES-128 in CBC mode. `Dir` is [`bouncycastle_modes::Encrypting`] or
/// [`bouncycastle_modes::Decrypting`]; the wrong direction is a compile error, not a runtime check.
///
/// The IV is generated by encryption and returned alongside the ciphertext; it is never supplied.
///
/// ```
/// use bouncycastle_aes_lowmemory::AES_CBC_128;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{BlockCipherDecryptor, BlockCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey)
///     .expect("a 16-byte symmetric cipher key");
/// let plaintext = [[0u8; 16]; 3];
///
/// let (iv, ciphertext) = AES_CBC_128::<Encrypting>::encrypt_blocks(&key, &plaintext).unwrap();
/// let recovered = AES_CBC_128::<Decrypting>::decrypt_blocks(&key, &iv, &ciphertext).unwrap();
/// assert_eq!(recovered, plaintext);
/// ```
#[allow(non_camel_case_types)]
pub type AES_CBC_128<Dir> = Cbc<Aes128, Dir, 16, BLOCK_LEN>;

/// AES-192 in CBC mode. See [`AES_CBC_128`].
///
/// ```
/// use bouncycastle_aes_lowmemory::AES_CBC_192;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{BlockCipherDecryptor, BlockCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<24>::from_bytes_as_type(&[0x42; 24], KeyType::SymmetricCipherKey).unwrap();
/// let (iv, ct) = AES_CBC_192::<Encrypting>::encrypt_blocks(&key, &[[0u8; 16]; 2]).unwrap();
/// assert_eq!(AES_CBC_192::<Decrypting>::decrypt_blocks(&key, &iv, &ct).unwrap(), [[0u8; 16]; 2]);
/// ```
#[allow(non_camel_case_types)]
pub type AES_CBC_192<Dir> = Cbc<Aes192, Dir, 24, BLOCK_LEN>;

/// AES-256 in CBC mode. See [`AES_CBC_128`].
///
/// ```
/// use bouncycastle_aes_lowmemory::AES_CBC_256;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{BlockCipherDecryptor, BlockCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<32>::from_bytes_as_type(&[0x42; 32], KeyType::SymmetricCipherKey).unwrap();
/// let (iv, ct) = AES_CBC_256::<Encrypting>::encrypt_blocks(&key, &[[0u8; 16]; 2]).unwrap();
/// assert_eq!(AES_CBC_256::<Decrypting>::decrypt_blocks(&key, &iv, &ct).unwrap(), [[0u8; 16]; 2]);
/// ```
#[allow(non_camel_case_types)]
pub type AES_CBC_256<Dir> = Cbc<Aes256, Dir, 32, BLOCK_LEN>;
