//! Type aliases for Camellia in CBC mode (NIST SP 800-38A Sec 6.2; the `id-camellia*-cbc`
//! algorithms of RFC 3713 Sec 3).
//!
//! `bouncycastle-modes` is deliberately cipher-agnostic, so `Cbc` takes the permutation, the
//! direction, and the `KEY_LEN` / `BLOCK_LEN` const parameters. These aliases pin the Camellia
//! values so callers never spell them out. They add nothing to the engine: the permutation still
//! implements none of the data-encryption traits itself (see the crate docs), the mode does.

use crate::{BLOCK_LEN, Camellia_128, Camellia_192, Camellia_256};
use bouncycastle_modes::Cbc;

/// Camellia-128 in CBC mode. `Dir` is [`bouncycastle_modes::Encrypting`] or
/// [`bouncycastle_modes::Decrypting`]; the wrong direction is a compile error, not a runtime check.
///
/// The IV is generated by encryption and returned; it is never supplied. Encryption and decryption
/// work in place.
///
/// ```
/// use bouncycastle_camellia::Camellia_CBC_128;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{BlockCipherDecryptor, BlockCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey)
///     .expect("a 16-byte symmetric cipher key");
/// // 48 bytes: three whole blocks. The length is checked at compile time.
/// let message = [0u8; 48];
/// let mut data = message;
/// let iv = Camellia_CBC_128::<Encrypting>::encrypt(&key, &mut data).unwrap();
/// assert_ne!(data, message);
/// Camellia_CBC_128::<Decrypting>::decrypt(&key, &iv, &mut data).unwrap();
/// assert_eq!(data, message);
///
/// // Streaming, a few blocks at a time:
/// let (mut enc, iv) = Camellia_CBC_128::<Encrypting>::do_encrypt_init(&key).unwrap();
/// let mut first = [0u8; 16];
/// let mut rest = [1u8; 32];
/// enc.do_encrypt(&mut first).unwrap();
/// enc.do_encrypt(&mut rest).unwrap();
/// let mut dec = Camellia_CBC_128::<Decrypting>::do_decrypt_init(&key, &iv).unwrap();
/// dec.do_decrypt(&mut first).unwrap();
/// dec.do_decrypt(&mut rest).unwrap();
/// assert_eq!(first, [0u8; 16]);
/// assert_eq!(rest, [1u8; 32]);
/// ```
///
/// A length that is not a whole number of blocks is a **compile** error, not a runtime one:
///
/// ```compile_fail
/// use bouncycastle_camellia::Camellia_CBC_128;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::BlockCipherEncryptor;
/// use bouncycastle_modes::Encrypting;
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey).unwrap();
/// // 47 bytes is not a multiple of 16: the inline const assertion in `encrypt` fails to compile.
/// let _ = Camellia_CBC_128::<Encrypting>::encrypt(&key, &mut [0u8; 47]);
/// ```
#[allow(non_camel_case_types)]
pub type Camellia_CBC_128<Dir> = Cbc<Camellia_128, Dir, 16, BLOCK_LEN>;

/// Camellia-192 in CBC mode. See [`Camellia_CBC_128`]; only the key length differs.
#[allow(non_camel_case_types)]
pub type Camellia_CBC_192<Dir> = Cbc<Camellia_192, Dir, 24, BLOCK_LEN>;

/// Camellia-256 in CBC mode. See [`Camellia_CBC_128`]; only the key length differs.
#[allow(non_camel_case_types)]
pub type Camellia_CBC_256<Dir> = Cbc<Camellia_256, Dir, 32, BLOCK_LEN>;
