//! Type aliases for Camellia (RFC 3713) in CBC mode (NIST SP 800-38A Sec 6.2), with padding.
//!
//! `bouncycastle-modes` is deliberately cipher-agnostic, so `Cbc` takes the permutation, the
//! direction, and the `KEY_LEN` / `BLOCK_LEN` const parameters, and `bouncycastle-padding`'s
//! adapters take five more. These aliases pin all of them except the two choices a caller actually
//! makes: the direction and the padding scheme. They add nothing to the engine: the permutation
//! still implements none of the data-encryption traits itself (see the crate docs), the mode does.
//!
//! ```text
//! Camellia_CBC_128<Encrypting, PKCS7>
//! Camellia_CBC_256<Decrypting, NoPadding>
//! ```
//!
//! CBC is defined only on whole blocks (SP 800-38A Sec 5.2), so CBC on data of any other length is
//! always CBC *plus a padding scheme*, and the scheme changes the ciphertext and must be agreed by
//! both ends. Naming it in the type makes that choice explicit and makes a mismatched pair a
//! compile error. The block-aligned API -- whole blocks in place, length checked at compile time --
//! is `bouncycastle_modes::Cbc` itself, which these wrap. See
//! [`PaddedMode`](bouncycastle_padding::PaddedMode) for how one alias covers both directions.

use crate::{BLOCK_LEN, Camellia_128, Camellia_192, Camellia_256};
use bouncycastle_modes::{Cbc, Decrypting, Encrypting};
use bouncycastle_padding::PaddedMode;

// Imports needed for docs
#[allow(unused_imports)]
use bouncycastle_core::traits::{SymmetricCipherDecryptor, SymmetricCipherEncryptor};
#[allow(unused_imports)]
use bouncycastle_padding::{NoPadding, PKCS7};
// end of imports needed for docs

/// Camellia-128 in CBC mode with a padding scheme.
///
/// `Dir` is [`Encrypting`] or [`Decrypting`] and `Pad` is [`PKCS7`] or [`NoPadding`]; the wrong
/// direction is a compile error, not a runtime check. The IV is generated by encryption and
/// returned; it is never supplied.
///
/// ```
/// use bouncycastle_camellia::Camellia_CBC_128;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{SymmetricCipherDecryptor, SymmetricCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
/// use bouncycastle_padding::PKCS7;
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey)
///     .expect("a 16-byte symmetric cipher key");
/// let message = b"a message of no particular length";
///
/// let (iv, ciphertext) =
///     Camellia_CBC_128::<Encrypting, PKCS7>::encrypt(&key, message).expect("encryption");
/// let recovered =
///     Camellia_CBC_128::<Decrypting, PKCS7>::decrypt(&key, &iv, &ciphertext).expect("decryption");
/// assert_eq!(recovered, message);
/// ```
#[allow(non_camel_case_types)]
pub type Camellia_CBC_128<Dir, Pad> = <Dir as PaddedMode<
    Cbc<Camellia_128, Encrypting, 16, BLOCK_LEN>,
    Cbc<Camellia_128, Decrypting, 16, BLOCK_LEN>,
    Pad,
    16,
    BLOCK_LEN,
    BLOCK_LEN,
>>::Mode;

/// Camellia-192 in CBC mode with a padding scheme.
///
/// `Dir` is [`Encrypting`] or [`Decrypting`] and `Pad` is [`PKCS7`] or [`NoPadding`]; the wrong
/// direction is a compile error, not a runtime check. The IV is generated by encryption and
/// returned; it is never supplied.
///
/// ```
/// use bouncycastle_camellia::Camellia_CBC_192;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{SymmetricCipherDecryptor, SymmetricCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
/// use bouncycastle_padding::PKCS7;
///
/// let key = KeyMaterial::<24>::from_bytes_as_type(&[0x42; 24], KeyType::SymmetricCipherKey)
///     .expect("a 24-byte symmetric cipher key");
/// let message = b"a message of no particular length";
///
/// let (iv, ciphertext) =
///     Camellia_CBC_192::<Encrypting, PKCS7>::encrypt(&key, message).expect("encryption");
/// let recovered =
///     Camellia_CBC_192::<Decrypting, PKCS7>::decrypt(&key, &iv, &ciphertext).expect("decryption");
/// assert_eq!(recovered, message);
/// ```
#[allow(non_camel_case_types)]
pub type Camellia_CBC_192<Dir, Pad> = <Dir as PaddedMode<
    Cbc<Camellia_192, Encrypting, 24, BLOCK_LEN>,
    Cbc<Camellia_192, Decrypting, 24, BLOCK_LEN>,
    Pad,
    24,
    BLOCK_LEN,
    BLOCK_LEN,
>>::Mode;

/// Camellia-256 in CBC mode with a padding scheme.
///
/// `Dir` is [`Encrypting`] or [`Decrypting`] and `Pad` is [`PKCS7`] or [`NoPadding`]; the wrong
/// direction is a compile error, not a runtime check. The IV is generated by encryption and
/// returned; it is never supplied.
///
/// ```
/// use bouncycastle_camellia::Camellia_CBC_256;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{SymmetricCipherDecryptor, SymmetricCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
/// use bouncycastle_padding::PKCS7;
///
/// let key = KeyMaterial::<32>::from_bytes_as_type(&[0x42; 32], KeyType::SymmetricCipherKey)
///     .expect("a 32-byte symmetric cipher key");
/// let message = b"a message of no particular length";
///
/// let (iv, ciphertext) =
///     Camellia_CBC_256::<Encrypting, PKCS7>::encrypt(&key, message).expect("encryption");
/// let recovered =
///     Camellia_CBC_256::<Decrypting, PKCS7>::decrypt(&key, &iv, &ciphertext).expect("decryption");
/// assert_eq!(recovered, message);
/// ```
#[allow(non_camel_case_types)]
pub type Camellia_CBC_256<Dir, Pad> = <Dir as PaddedMode<
    Cbc<Camellia_256, Encrypting, 32, BLOCK_LEN>,
    Cbc<Camellia_256, Decrypting, 32, BLOCK_LEN>,
    Pad,
    32,
    BLOCK_LEN,
    BLOCK_LEN,
>>::Mode;
