//! Type aliases for Camellia (RFC 3713) in CTR mode (NIST SP 800-38A Sec 6.5).
//!
//! `bouncycastle-modes` is deliberately cipher-agnostic, so `Ctr` takes the permutation, the
//! direction, and the `KEY_LEN` / `BLOCK_LEN` / `INIT_DATA_LEN` const parameters. These aliases pin
//! the Camellia values so callers never spell them out. They add nothing to the engine: the
//! permutation still implements none of the data-encryption traits itself (see the crate docs), the
//! mode does.
//!
//! # The nonce length is 12, so the counter is 4
//!
//! `Ctr` splits the counter block into a nonce and a counter by the length of its init data, and
//! these aliases choose a **12-byte nonce**, leaving the 4-byte counter that is the mode's maximum.
//! That allows 2^32 blocks -- 64 GiB -- in one message, and past it the mode errors rather than
//! repeating keystream. A shorter message limit in exchange for more nonce bits is available by
//! naming `Ctr` directly with a 13, 14 or 15-byte nonce.
//!
//! RFC 5528, "Camellia Counter Mode and Camellia Counter with CBC-MAC Mode Algorithms", divides the
//! same 16-byte counter block differently -- a 4-octet nonce, an 8-octet IV and a 4-octet block
//! counter that starts at **one** rather than zero, which is the IPsec convention rather than a
//! property of Camellia. Its nine test vectors therefore begin one block into the keystream these
//! aliases generate, so `tests/stream_mode_tests.rs` uses them to pin a reference CTR built from
//! the SP 800-38A Sec 6.5 equations over the permutation, and holds these aliases to that
//! reference on the counter blocks they do produce.

use crate::{BLOCK_LEN, Camellia_128, Camellia_192, Camellia_256};
use bouncycastle_modes::Ctr;

/// The nonce length these aliases use, leaving a 4-byte counter.
pub const CTR_NONCE_LEN: usize = 12;

/// Camellia-128 in CTR mode with a 12-byte nonce. `Dir` is [`bouncycastle_modes::Encrypting`] or
/// [`bouncycastle_modes::Decrypting`]; the wrong direction is a compile error, not a runtime check.
///
/// CTR is a stream cipher, so the data is a `&mut [u8]` of any length and the ciphertext is exactly
/// as long as the plaintext. The nonce is generated by encryption and returned; it is never
/// supplied. Encryption and decryption work in place, and are the same operation.
///
/// ```
/// use bouncycastle_camellia::Camellia_CTR_128;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{StreamCipherDecryptor, StreamCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey)
///     .expect("a 16-byte symmetric cipher key");
/// // 47 bytes: a stream cipher does not need a whole number of blocks.
/// let message = [0u8; 47];
/// let mut data = message;
/// let (_, nonce) = Camellia_CTR_128::<Encrypting>::encrypt(&key, &mut data).unwrap();
/// assert_eq!(nonce.len(), 12);
/// assert_ne!(data, message);
/// Camellia_CTR_128::<Decrypting>::decrypt(&key, &nonce, &mut data).unwrap();
/// assert_eq!(data, message);
///
/// // Streaming, at any byte boundary:
/// let (mut enc, nonce) = Camellia_CTR_128::<Encrypting>::do_encrypt_init(&key).unwrap();
/// let mut first = [0u8; 5];
/// let mut rest = [1u8; 30];
/// enc.do_encrypt(&mut first).unwrap();
/// enc.do_encrypt(&mut rest).unwrap();
/// let mut dec = Camellia_CTR_128::<Decrypting>::do_decrypt_init(&key, &nonce).unwrap();
/// dec.do_decrypt(&mut first).unwrap();
/// dec.do_decrypt(&mut rest).unwrap();
/// assert_eq!(first, [0u8; 5]);
/// assert_eq!(rest, [1u8; 30]);
/// ```
#[allow(non_camel_case_types)]
pub type Camellia_CTR_128<Dir> = Ctr<Camellia_128, Dir, 16, BLOCK_LEN, CTR_NONCE_LEN>;

/// Camellia-192 in CTR mode with a 12-byte nonce. See [`Camellia_CTR_128`].
///
/// ```
/// use bouncycastle_camellia::Camellia_CTR_192;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{StreamCipherDecryptor, StreamCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<24>::from_bytes_as_type(&[0x42; 24], KeyType::SymmetricCipherKey).unwrap();
/// let mut data = [0u8; 30];
/// let (_, nonce) = Camellia_CTR_192::<Encrypting>::encrypt(&key, &mut data).unwrap();
/// Camellia_CTR_192::<Decrypting>::decrypt(&key, &nonce, &mut data).unwrap();
/// assert_eq!(data, [0u8; 30]);
/// ```
#[allow(non_camel_case_types)]
pub type Camellia_CTR_192<Dir> = Ctr<Camellia_192, Dir, 24, BLOCK_LEN, CTR_NONCE_LEN>;

/// Camellia-256 in CTR mode with a 12-byte nonce. See [`Camellia_CTR_128`].
///
/// ```
/// use bouncycastle_camellia::Camellia_CTR_256;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{StreamCipherDecryptor, StreamCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// let key = KeyMaterial::<32>::from_bytes_as_type(&[0x42; 32], KeyType::SymmetricCipherKey).unwrap();
/// let mut data = [0u8; 30];
/// let (_, nonce) = Camellia_CTR_256::<Encrypting>::encrypt(&key, &mut data).unwrap();
/// Camellia_CTR_256::<Decrypting>::decrypt(&key, &nonce, &mut data).unwrap();
/// assert_eq!(data, [0u8; 30]);
/// ```
#[allow(non_camel_case_types)]
pub type Camellia_CTR_256<Dir> = Ctr<Camellia_256, Dir, 32, BLOCK_LEN, CTR_NONCE_LEN>;
