//! Type alias for TDES in CBC mode (NIST SP 800-38A Sec 6.2; "TCBC" in SP 800-38A Appendix E),
//! with padding.
//!
//! `bouncycastle-modes` is deliberately cipher-agnostic, so `Cbc` takes the permutation, the
//! direction, and the `KEY_LEN` / `BLOCK_LEN` const parameters, and `bouncycastle-padding`'s
//! adapters take five more. This alias pins all of them except the two choices a caller actually
//! makes: the direction and the padding scheme. It adds nothing to the engine -- the permutation
//! still implements none of the data-encryption traits itself (see the crate docs), the mode does.
//!
//! ```text
//! TDES_CBC<Encrypting, PKCS7>   // TDES, CBC, PKCS#7 padded, encrypting
//! TDES_CBC<Decrypting, NoPadding>
//! ```
//!
//! # Why the padding is part of the alias
//!
//! CBC is defined only on whole blocks (SP 800-38A Sec 5.2), and the recommendation puts the
//! formatting of anything else outside its scope (Appendix A). So CBC on real data is always CBC
//! *plus a padding scheme*, and the scheme is not an implementation detail: it changes the
//! ciphertext, and both ends must agree on it. Naming it in the type makes that choice explicit at
//! every use, and makes a mismatched pair a compile error rather than a decryption that returns
//! plausible-looking rubbish.
//!
//! The two schemes `bouncycastle-padding` provides are [`PKCS7`], which is what almost everyone
//! means by "padded CBC" (RFC 5652 s. 6.3; Java's `DESede/CBC/PKCS5Padding`), and [`NoPadding`],
//! which adds nothing and instead *rejects* a message that is not a whole number of blocks --
//! useful for formats already defined on block boundaries, where silently padding would be wrong.
//!
//! # This is the arbitrary-length API
//!
//! A padded alias implements [`SimpleCipherEncryptor`] / [`SimpleCipherDecryptor`], not the
//! block traits: `encrypt_out` / `decrypt_out` and the streaming `do_update_out` / `do_final`, all
//! taking a `&[u8]` of any length. The block-aligned API, with its compile-time length checks and
//! its in-place data methods, is `bouncycastle_modes::Cbc` itself, which this wraps:
//!
//! ```text
//! bouncycastle_modes::Cbc<TDES, Encrypting, 24, 8>   // block-aligned, in place
//! TDES_CBC<Encrypting, PKCS7>                        // any length, padded
//! ```
//!
//! # How one alias covers both directions
//!
//! `PaddedEncryptor` and `PaddedDecryptor` are two distinct types, so a plain type alias cannot
//! select between them on a `Dir` parameter. [`PaddedMode`] does it instead: it is implemented for
//! each direction marker and projects to the right adapter, and the alias is written as that
//! projection. The only visible consequence is that `Dir` must be
//! [`Encrypting`](bouncycastle_modes::Encrypting) or
//! [`Decrypting`](bouncycastle_modes::Decrypting), which was already true.

use crate::padded_mode::PaddedMode;
use crate::{BLOCK_LEN, KEY_LEN, KEY_LEN_2KEY, TDES, TDES2Key};
use bouncycastle_modes::{Cbc, Decrypting, Encrypting};
use bouncycastle_padding::PaddedDecryptor;

// Imports needed for docs
#[allow(unused_imports)]
use bouncycastle_core::traits::{SimpleCipherDecryptor, SimpleCipherEncryptor};
#[allow(unused_imports)]
use bouncycastle_padding::{NoPadding, PKCS7, PaddedEncryptor};
// end of imports needed for docs

/// TDES in CBC mode with a padding scheme.
///
/// `Dir` is [`Encrypting`] or [`Decrypting`] and `Pad` is [`PKCS7`] or [`NoPadding`]; the wrong
/// direction is a compile error, not a runtime check. The IV is generated by encryption and
/// returned; it is never supplied. It is one block: 8 bytes.
///
/// ```
/// use bouncycastle_tdes::TDES_CBC;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{SimpleCipherDecryptor, SimpleCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
/// use bouncycastle_padding::PKCS7;
///
/// type Enc = TDES_CBC<Encrypting, PKCS7>;
/// type Dec = TDES_CBC<Decrypting, PKCS7>;
///
/// // Three distinct component keys; see `TDES` for what a key bundle must satisfy.
/// let bytes: [u8; 24] = core::array::from_fn(|i| (i as u8).wrapping_mul(7).wrapping_add(1));
/// let key = KeyMaterial::<24>::from_bytes_as_type(&bytes, KeyType::SymmetricCipherKey)
///     .expect("a 24-byte symmetric cipher key");
///
/// // 5 bytes: PKCS#7 pads it to one block, so the padding does the work CBC cannot.
/// let message = b"hello";
/// let mut ciphertext = [0u8; 8];
/// let (iv, written) = Enc::encrypt_out(&key, message, &mut ciphertext).expect("encryption");
/// assert_eq!(written, 8);
///
/// let mut plaintext = [0u8; 8];
/// let n = Dec::decrypt_out(&key, &iv, &ciphertext, &mut plaintext).expect("decryption");
/// assert_eq!(&plaintext[..n], message);
/// ```
///
/// With [`NoPadding`] nothing is added, and a message that is not a whole number of blocks is an
/// error at `do_final` rather than something silently padded:
///
/// ```
/// use bouncycastle_tdes::TDES_CBC;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::SimpleCipherEncryptor;
/// use bouncycastle_modes::Encrypting;
/// use bouncycastle_padding::NoPadding;
///
/// type Enc = TDES_CBC<Encrypting, NoPadding>;
///
/// let bytes: [u8; 24] = core::array::from_fn(|i| (i as u8).wrapping_mul(7).wrapping_add(1));
/// let key = KeyMaterial::<24>::from_bytes_as_type(&bytes, KeyType::SymmetricCipherKey).unwrap();
///
/// // A whole block is fine, and comes out the same length.
/// let mut out = [0u8; 8];
/// let (_iv, written) = Enc::encrypt_out(&key, &[0u8; 8], &mut out).expect("aligned");
/// assert_eq!(written, 8);
///
/// // Five bytes is not, and is refused rather than padded.
/// let mut out = [0u8; 8];
/// assert!(Enc::encrypt_out(&key, b"hello", &mut out).is_err());
/// ```
///
/// The padding scheme is part of the type, so the two schemes are different types and cannot be
/// interchanged. A value built with one will not satisfy a binding annotated with the other:
///
/// ```compile_fail
/// use bouncycastle_tdes::TDES_CBC;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::SimpleCipherEncryptor;
/// use bouncycastle_modes::Encrypting;
/// use bouncycastle_padding::{NoPadding, PKCS7};
///
/// let bytes: [u8; 24] = core::array::from_fn(|i| (i as u8).wrapping_mul(7).wrapping_add(1));
/// let key = KeyMaterial::<24>::from_bytes_as_type(&bytes, KeyType::SymmetricCipherKey).unwrap();
///
/// // Built as NoPadding, annotated as PKCS7: mismatched types.
/// let (enc, _iv) = TDES_CBC::<Encrypting, NoPadding>::do_encrypt_init(&key).unwrap();
/// let _mismatched: TDES_CBC<Encrypting, PKCS7> = enc;
/// ```
#[allow(non_camel_case_types)]
pub type TDES_CBC<Dir, Pad> = <Dir as PaddedMode<
    Cbc<TDES, Encrypting, KEY_LEN, BLOCK_LEN>,
    Cbc<TDES, Decrypting, KEY_LEN, BLOCK_LEN>,
    Pad,
    BLOCK_LEN,
>>::Mode;

/// Two-key TDES in CBC mode with a padding scheme, **decryption only**.
///
/// `Pad` is [`PKCS7`] or [`NoPadding`]. There is no direction parameter: two-key TDEA is disallowed
/// for encryption (SP 800-131A Rev 2 Table 1), so this is the [`PaddedDecryptor`] alone, and
/// `Cbc<TDES2Key, Encrypting, ..>` does not compile; see [`TDES2Key`]. The IV is one 8-byte block,
/// supplied by the caller as it was received.
///
/// ```
/// use bouncycastle_tdes::TDES2_CBC;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::SimpleCipherDecryptor;
/// use bouncycastle_padding::NoPadding;
///
/// // NIST CAVP TCBCMMT2.rsp, [DECRYPT] COUNT = 0: KEY1 || KEY2 (KEY3 = KEY1).
/// let key = KeyMaterial::<16>::from_bytes_as_type(
///     &[0xbc, 0xfe, 0x7f, 0x25, 0xf2, 0xb0, 0xa7, 0x2c,
///       0x62, 0x76, 0xae, 0x1f, 0x38, 0x9d, 0x8a, 0xe9],
///     KeyType::SymmetricCipherKey,
/// ).expect("a 16-byte symmetric cipher key");
/// let iv = [0xf2, 0x9d, 0x4b, 0xa5, 0x17, 0x2f, 0xd2, 0x97];
/// let ciphertext = [0x1b, 0x38, 0x89, 0xc9, 0xdb, 0xe1, 0x0d, 0x03];
///
/// let plaintext = TDES2_CBC::<NoPadding>::decrypt(&key, &iv, &ciphertext).expect("decryption");
/// assert_eq!(plaintext, [0x06, 0x11, 0xa4, 0x74, 0xfb, 0x09, 0x09, 0x78]);
/// ```
#[allow(non_camel_case_types)]
pub type TDES2_CBC<Pad> = PaddedDecryptor<
    Cbc<TDES2Key, Decrypting, KEY_LEN_2KEY, BLOCK_LEN>,
    Pad,
    KEY_LEN_2KEY,
    BLOCK_LEN,
    BLOCK_LEN,
>;
