//! Type alias for TDES in CFB mode (NIST SP 800-38A Sec 6.3), full-block segment.
//!
//! `bouncycastle-modes` is deliberately cipher-agnostic, so `Cfb` takes the permutation, the
//! direction, and the `KEY_LEN` / `BLOCK_LEN` const parameters. This alias pins the TDES values so
//! callers never spell them out. It adds nothing to the engine: the permutation still implements
//! none of the data-encryption traits itself (see the crate docs), the mode does.
//!
//! The segment size is the full block, so this is **CFB64** -- the `s = 64` case of the TCFB mode
//! that SP 800-38A Appendix E says is "equivalent to the CFB mode in this recommendation, with the
//! TDEA as the underlying block cipher". SP 800-38A's `s = 8` variant is a different,
//! non-interoperable mode with its own alias, [`TDES_CFB8`](crate::TDES_CFB8); `s = 1` is not
//! implemented. See the `bouncycastle_modes::Cfb` docs.

use crate::{BLOCK_LEN, KEY_LEN, KEY_LEN_2KEY, TDES, TDES2Key};
use bouncycastle_modes::{Cfb, Decrypting};

/// TDES in CFB64 mode. `Dir` is [`bouncycastle_modes::Encrypting`] or
/// [`bouncycastle_modes::Decrypting`]; the wrong direction is a compile error, not a runtime check.
///
/// CFB is a stream cipher, so the data is a `&mut [u8]` of any length and the ciphertext is exactly
/// as long as the plaintext. The IV is one block (8 bytes), generated by encryption and returned;
/// it is never supplied. Encryption and decryption work in place.
///
/// ```
/// use bouncycastle_tdes::TDES_CFB;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{StreamCipherDecryptor, StreamCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// // Three distinct component keys; see `TDES` for what a key bundle must satisfy.
/// let bytes: [u8; 24] = core::array::from_fn(|i| (i as u8).wrapping_mul(7).wrapping_add(1));
/// let key = KeyMaterial::<24>::from_bytes_as_type(&bytes, KeyType::SymmetricCipherKey)
///     .expect("a 24-byte symmetric cipher key");
/// // 47 bytes: a stream cipher does not need a whole number of blocks.
/// let message = [0u8; 47];
/// let mut data = message;
/// let iv = TDES_CFB::<Encrypting>::encrypt(&key, &mut data).unwrap();
/// assert_ne!(data, message);
/// TDES_CFB::<Decrypting>::decrypt(&key, &iv, &mut data).unwrap();
/// assert_eq!(data, message);
///
/// // Streaming, at any byte boundary:
/// let (mut enc, iv) = TDES_CFB::<Encrypting>::do_encrypt_init(&key).unwrap();
/// let mut first = [0u8; 5];
/// let mut rest = [1u8; 30];
/// enc.do_encrypt(&mut first).unwrap();
/// enc.do_encrypt(&mut rest).unwrap();
/// let mut dec = TDES_CFB::<Decrypting>::do_decrypt_init(&key, &iv).unwrap();
/// dec.do_decrypt(&mut first).unwrap();
/// dec.do_decrypt(&mut rest).unwrap();
/// assert_eq!(first, [0u8; 5]);
/// assert_eq!(rest, [1u8; 30]);
/// ```
#[allow(non_camel_case_types)]
pub type TDES_CFB<Dir> = Cfb<TDES, Dir, KEY_LEN, BLOCK_LEN>;

/// Two-key TDES in CFB64 mode, **decryption only** (SP 800-131A Rev 2 Table 1). No direction
/// parameter: this is the `Decrypting` direction, and `Cfb<TDES2Key, Encrypting, ..>` does not
/// compile; see [`TDES2Key`]. The IV is one 8-byte block, supplied by the caller as received.
///
/// ```
/// use bouncycastle_tdes::TDES2_CFB;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::StreamCipherDecryptor;
///
/// // NIST CAVP TCFB64MMT2.rsp, [DECRYPT] COUNT = 0: KEY1 || KEY2 (KEY3 = KEY1).
/// let key = KeyMaterial::<16>::from_bytes_as_type(
///     &[0x9e, 0xe0, 0xb5, 0x9b, 0x25, 0x86, 0x51, 0x54,
///       0x58, 0x85, 0x51, 0x34, 0x1c, 0x4f, 0xef, 0x9e],
///     KeyType::SymmetricCipherKey,
/// ).expect("a 16-byte symmetric cipher key");
/// let iv = [0x6e, 0x37, 0xd1, 0x97, 0x37, 0x6d, 0xb5, 0x95];
/// let mut data = [0x63, 0xca, 0xd5, 0x22, 0x60, 0xe0, 0xa1, 0xcd];
///
/// TDES2_CFB::decrypt(&key, &iv, &mut data).expect("decryption");
/// assert_eq!(data, [0xdc, 0xd3, 0xcf, 0x97, 0x46, 0xd6, 0xe4, 0x2b]);
/// ```
#[allow(non_camel_case_types)]
pub type TDES2_CFB = Cfb<TDES2Key, Decrypting, KEY_LEN_2KEY, BLOCK_LEN>;
