//! Type alias for TDES in CFB8 mode (NIST SP 800-38A Sec 6.3, `s = 8`).
//!
//! `bouncycastle-modes` is deliberately cipher-agnostic, so `Cfb8` takes the permutation, the
//! direction, and the `KEY_LEN` / `BLOCK_LEN` const parameters. This alias pins the TDES values so
//! callers never spell them out. It adds nothing to the engine: the permutation still implements
//! none of the data-encryption traits itself (see the crate docs), the mode does.
//!
//! CFB8 is a **different, non-interoperable mode** from CFB64, not a variant of it: their
//! ciphertexts differ from the second byte, and it costs a full TDES call per byte, eight times
//! the work of [`TDES_CFB`](crate::TDES_CFB). It is the `s = 8` case of the TCFB mode of SP 800-38A
//! Appendix E. See the `bouncycastle_modes::Cfb8` docs for when that is the right trade.

use crate::{BLOCK_LEN, KEY_LEN, KEY_LEN_2KEY, TDES, TDES2Key};
use bouncycastle_modes::{Cfb8, Decrypting};

/// TDES in CFB8 mode. `Dir` is [`bouncycastle_modes::Encrypting`] or
/// [`bouncycastle_modes::Decrypting`]; the wrong direction is a compile error, not a runtime check.
///
/// CFB8 is a stream cipher with a one-byte segment, so the data is a `&mut [u8]` of any length and
/// the ciphertext is exactly as long as the plaintext. The IV is one block (8 bytes), generated by
/// encryption and returned; it is never supplied. Encryption and decryption work in place.
///
/// ```
/// use bouncycastle_tdes::{TDES_CFB8, TDES_CFB};
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::{StreamCipherDecryptor, StreamCipherEncryptor};
/// use bouncycastle_modes::{Decrypting, Encrypting};
///
/// // Three distinct component keys; see `TDES` for what a key bundle must satisfy.
/// let bytes: [u8; 24] = core::array::from_fn(|i| (i as u8).wrapping_mul(7).wrapping_add(1));
/// let key = KeyMaterial::<24>::from_bytes_as_type(&bytes, KeyType::SymmetricCipherKey)
///     .expect("a 24-byte symmetric cipher key");
/// // 5 bytes: CFB8's segment is one byte, so any length at all is fine.
/// let message = *b"hello";
/// let mut data = message;
/// let iv = TDES_CFB8::<Encrypting>::encrypt(&key, &mut data).unwrap();
/// assert_ne!(data, message);
/// TDES_CFB8::<Decrypting>::decrypt(&key, &iv, &mut data).unwrap();
/// assert_eq!(data, message);
///
/// // CFB8 and CFB64 are not interchangeable: same key, same IV, different ciphertext.
/// let mut as_cfb8 = message;
/// let iv = TDES_CFB8::<Encrypting>::encrypt(&key, &mut as_cfb8).unwrap();
/// let mut as_cfb64 = as_cfb8;
/// TDES_CFB::<Decrypting>::decrypt(&key, &iv, &mut as_cfb64).unwrap();
/// assert_ne!(as_cfb64, message);
/// ```
#[allow(non_camel_case_types)]
pub type TDES_CFB8<Dir> = Cfb8<TDES, Dir, KEY_LEN, BLOCK_LEN>;

/// Two-key TDES in CFB8 mode, **decryption only** (SP 800-131A Rev 2 Table 1). No direction
/// parameter: this is the `Decrypting` direction, and `Cfb8<TDES2Key, Encrypting, ..>` does not
/// compile; see [`TDES2Key`]. The IV is one 8-byte block, supplied by the caller as received.
///
/// ```
/// use bouncycastle_tdes::TDES2_CFB8;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_core::traits::StreamCipherDecryptor;
///
/// // NIST CAVP TCFB8MMT2.rsp, [DECRYPT] COUNT = 0: KEY1 || KEY2 (KEY3 = KEY1).
/// let key = KeyMaterial::<16>::from_bytes_as_type(
///     &[0xfb, 0x97, 0x8a, 0x0b, 0x6d, 0xc2, 0xc4, 0x67,
///       0xe3, 0xcb, 0x52, 0x32, 0x9d, 0xe9, 0x51, 0x61],
///     KeyType::SymmetricCipherKey,
/// ).expect("a 16-byte symmetric cipher key");
/// let iv = [0x8b, 0x97, 0x57, 0x9e, 0xa5, 0xac, 0x30, 0x0f];
/// let mut data = [0x05];
///
/// TDES2_CFB8::decrypt(&key, &iv, &mut data).expect("decryption");
/// assert_eq!(data, [0x80]);
/// ```
#[allow(non_camel_case_types)]
pub type TDES2_CFB8 = Cfb8<TDES2Key, Decrypting, KEY_LEN_2KEY, BLOCK_LEN>;
