//! `ECDSAP521`: FIPS 186-5 §6.4.1 (signature generation, deterministic per §6.3.2/Appendix A.3.3
//! by default) and §6.4.2 (verification), fixed to SHA-512. Identical in shape to
//! [`crate::ecdsa_p384`] -- see [`crate::ecdsa_p256`]'s docs for the shared reasoning (why
//! `x_affine_of_signing_point` exists, the `ctx`/ignore-it stance) -- with P-521's types, SHA-512,
//! and one difference `e_from_hash` documents: unlike P-256/SHA-256 and P-384/SHA-384, `len(n) =
//! 521` and `hashlen = 512` are not equal here, though `len(n) >= hashlen` still holds, so `E = H`
//! still needs no truncation (FIPS 186-5 §6.4.1 step 2a).

use crate::keys_p521::{
    ECDSAP521PrivateKey, ECDSAP521PublicKey, EXTRA_BITS_DRBG_OUTPUT_LEN, PK_LEN, SK_LEN,
    reduce_wide_bits_mod_n_minus_1,
};
use crate::rfc6979_p521;
use bouncycastle_core::errors::SignatureError;
use bouncycastle_core::traits::{Hash, RNG, SignatureVerifier, Signer};
use bouncycastle_ec::nat;
use bouncycastle_ec::p521::P521FieldElement;
use bouncycastle_ec::p521_comb::comb_multiply_base_point;
use bouncycastle_ec::p521_point::P521JacobianPoint;
use bouncycastle_ec::p521_scalar::{N_LIMBS, P521PublicScalar, P521Scalar, P521ScalarField};
use bouncycastle_ec::p521_sec1;
use bouncycastle_ec::p521_wnaf::shamir_multiply;
use bouncycastle_sha2::SHA512;
use bouncycastle_utils::secret::Secret;

/// Raw `r || s` signature length: two 66-byte field-width integers.
pub const SIG_LEN: usize = 132;

/// Upper bound on a DER-encoded P-521 signature (`r`, `s` each 66 bytes); see [`crate::der::max_len`].
pub const DER_SIG_MAX_LEN: usize = crate::der::max_len(66);

/// Streaming state for both `ECDSAP521`'s [`Signer`] and [`SignatureVerifier`] impls. See
/// [`crate::ecdsa_p256::ECDSAP256`]'s docs.
pub struct ECDSAP521 {
    hash: SHA512,
    sk: Option<ECDSAP521PrivateKey>,
    pk: Option<ECDSAP521PublicKey>,
}

/// `x * z^-2`, branch-free. See [`crate::ecdsa_p256::x_affine_of_signing_point`]'s docs.
fn x_affine_of_signing_point(point: &P521JacobianPoint) -> P521FieldElement {
    let z_inv = point.z.invert();
    point.x.mul(&z_inv.mul(&z_inv))
}

/// FIPS 186-5 §6.4.1 steps 4-12, given `k` already generated (step 3).
fn sign_with_k(
    sk: &ECDSAP521PrivateKey,
    e: &P521ScalarField,
    k: P521Scalar,
) -> Result<[u8; SIG_LEN], SignatureError> {
    let mut k_field = P521ScalarField::from_secret(&k);
    let mut k_inv = k_field.invert(); // step 4

    let r_point = comb_multiply_base_point(&k); // step 5
    let x_r = x_affine_of_signing_point(&r_point); // steps 6-7
    let r = P521ScalarField::from_limbs(x_r.to_limbs()); // step 8

    let mut d_field = P521ScalarField::from_secret(sk.scalar());
    let s = k_inv.mul(&e.add(&r.mul(&d_field))); // step 9

    // `k_field`, `k_inv` and `d_field` hold `k`, `k^-1` and `d`. Nothing below needs them, so they
    // are overwritten here rather than left legible on the stack after this returns -- placed
    // before step 11's check so that both ways out of the function are covered. `k` itself is a
    // `Secret` and scrubs when it drops; `e`, `r` and `s` are public by construction.
    k_field.zeroize();
    k_inv.zeroize();
    d_field.zeroize();

    if r_or_s_is_zero(&r, &s) {
        return Err(SignatureError::GenericError(
            "ECDSA signature generation produced r = 0 or s = 0; regenerate k and retry",
        ));
    }

    let mut sig = [0u8; SIG_LEN];
    sig[..66].copy_from_slice(&p521_sec1::be_bytes_from_limbs(&r.to_limbs()));
    sig[66..].copy_from_slice(&p521_sec1::be_bytes_from_limbs(&s.to_limbs()));
    Ok(sig)
}

/// `e` from a 64-byte (SHA-512) message hash: `E = H` (`len(n) = 521 >= hashlen = 512`, so no
/// truncation -- see the module docs), zero-extended into a 9-limb value, then Appendix B.2.1's
/// big-endian conversion.
fn e_from_hash(h: &[u8; 64]) -> P521ScalarField {
    let mut padded = [0u8; 66];
    padded[2..].copy_from_slice(h);
    P521ScalarField::from_limbs(p521_sec1::limbs_from_be_bytes(&padded))
}

/// FIPS 186-5 §6.4.1 step 11's `r = 0` or `s = 0` check. See
/// [`crate::ecdsa_p256::r_or_s_is_zero`]'s docs.
fn r_or_s_is_zero(r: &P521ScalarField, s: &P521ScalarField) -> bool {
    *r == P521ScalarField::ZERO || *s == P521ScalarField::ZERO
}

impl ECDSAP521 {
    /// FIPS 186-5 §6.4.1 with `k` generated by Appendix A.3.1 ("extra random bits") instead of the
    /// deterministic default. See [`crate::ecdsa_p256::ECDSAP256::sign_randomized`]'s docs. Draws
    /// A.3.1 step 3's `N + t` bits (`t = 71`, the byte-aligned width at or above `t = 64`) and
    /// reduces them with [`crate::keys_p521`]'s own copy of the wide-reduction machinery
    /// [`crate::extra_bits`] implements for P-256 -- see that module's docs.
    pub fn sign_randomized(
        sk: &ECDSAP521PrivateKey,
        msg: &[u8],
        rng: &mut dyn RNG,
    ) -> Result<[u8; SIG_LEN], SignatureError> {
        let h: [u8; 64] = SHA512::default().hash(msg)[..64].try_into().unwrap();
        let e = e_from_hash(&h);

        // Raw DRBG output, reduced below into the private key / per-message secret: held in
        // `Secret` so it is scrubbed when this function returns rather than left on the stack.
        let mut extra_bits = Secret::<[u8; EXTRA_BITS_DRBG_OUTPUT_LEN]>::new();
        rng.next_bytes_out(&mut *extra_bits).map_err(SignatureError::RNGError)?;
        let k = reduce_wide_bits_mod_n_minus_1(&*extra_bits);

        sign_with_k(sk, &e, k)
    }

    /// As [`Signer::sign`], but DER-encodes the result. See
    /// [`crate::ecdsa_p256::ECDSAP256::sign_der`]'s docs.
    pub fn sign_der(
        sk: &ECDSAP521PrivateKey,
        msg: &[u8],
        ctx: Option<&[u8]>,
    ) -> Result<([u8; DER_SIG_MAX_LEN], usize), SignatureError> {
        let raw = Self::sign(sk, msg, ctx)?;
        let mut out = [0u8; DER_SIG_MAX_LEN];
        let len = crate::der::encode(&raw[..66], &raw[66..], &mut out);
        Ok((out, len))
    }

    /// As [`SignatureVerifier::verify`], but expects a DER-encoded signature. See
    /// [`crate::ecdsa_p256::ECDSAP256::verify_der`]'s docs.
    pub fn verify_der(
        pk: &ECDSAP521PublicKey,
        msg: &[u8],
        ctx: Option<&[u8]>,
        sig: &[u8],
    ) -> Result<(), SignatureError> {
        let mut raw = [0u8; SIG_LEN];
        let (r_out, s_out) = raw.split_at_mut(66);
        crate::der::decode(sig, r_out, s_out).ok_or(SignatureError::SignatureVerificationFailed)?;
        Self::verify(pk, msg, ctx, &raw)
    }
}

impl Signer<ECDSAP521PrivateKey, SK_LEN, SIG_LEN> for ECDSAP521 {
    fn sign(
        sk: &ECDSAP521PrivateKey,
        msg: &[u8],
        ctx: Option<&[u8]>,
    ) -> Result<[u8; SIG_LEN], SignatureError> {
        let mut s = Self::sign_init(sk, ctx)?;
        s.sign_update(msg);
        s.sign_final()
    }

    fn sign_out(
        sk: &ECDSAP521PrivateKey,
        msg: &[u8],
        ctx: Option<&[u8]>,
        output: &mut [u8; SIG_LEN],
    ) -> Result<usize, SignatureError> {
        output.fill(0);
        *output = Self::sign(sk, msg, ctx)?;
        Ok(SIG_LEN)
    }

    fn sign_init(sk: &ECDSAP521PrivateKey, _ctx: Option<&[u8]>) -> Result<Self, SignatureError> {
        Ok(Self { hash: SHA512::default(), sk: Some(sk.clone()), pk: None })
    }

    fn sign_update(&mut self, msg_chunk: &[u8]) {
        self.hash.do_update(msg_chunk);
    }

    fn sign_final(self) -> Result<[u8; SIG_LEN], SignatureError> {
        let sk = self.sk.ok_or(SignatureError::GenericError(
            "sign_final called on a verify-initialized ECDSAP521; call verify_final instead",
        ))?;
        let mut h = [0u8; 64];
        self.hash.do_final_out(&mut h);
        let e = e_from_hash(&h);
        let k = rfc6979_p521::generate_k(sk.scalar(), &h);
        sign_with_k(&sk, &e, k)
    }

    fn sign_final_out(self, output: &mut [u8; SIG_LEN]) -> Result<usize, SignatureError> {
        output.fill(0);
        *output = self.sign_final()?;
        Ok(SIG_LEN)
    }
}

impl SignatureVerifier<ECDSAP521PublicKey, PK_LEN, SIG_LEN> for ECDSAP521 {
    fn verify(
        pk: &ECDSAP521PublicKey,
        msg: &[u8],
        ctx: Option<&[u8]>,
        sig: &[u8],
    ) -> Result<(), SignatureError> {
        let mut v = Self::verify_init(pk, ctx)?;
        v.verify_update(msg);
        v.verify_final(sig)
    }

    fn verify_init(pk: &ECDSAP521PublicKey, _ctx: Option<&[u8]>) -> Result<Self, SignatureError> {
        Ok(Self { hash: SHA512::default(), sk: None, pk: Some(*pk) })
    }

    fn verify_update(&mut self, msg_chunk: &[u8]) {
        self.hash.do_update(msg_chunk);
    }

    fn verify_final(self, sig: &[u8]) -> Result<(), SignatureError> {
        let pk = self.pk.ok_or(SignatureError::GenericError(
            "verify_final called on a sign-initialized ECDSAP521; call sign_final instead",
        ))?;
        // Exactly SIG_LEN, not "at least": the raw encoding is two fixed-width integers and
        // nothing else, so trailing bytes make this a different, malformed encoding rather than a
        // valid signature in a roomy buffer. Accepting them would let anyone turn one valid
        // signature into unlimited distinct byte strings that all verify -- malleability that
        // breaks any caller treating the signature as an opaque, comparable blob. This matches how
        // `SignaturePublicKey`/`SignaturePrivateKey::from_bytes` already reject an over-long
        // encoding here (see `core-test-framework`'s own `test_boundary_conditions`).
        if sig.len() != SIG_LEN {
            return Err(SignatureError::SignatureVerificationFailed);
        }

        let r_limbs = p521_sec1::limbs_from_be_bytes(&sig[..66].try_into().unwrap());
        let s_limbs = p521_sec1::limbs_from_be_bytes(&sig[66..132].try_into().unwrap());
        if !in_range(&r_limbs) || !in_range(&s_limbs) {
            return Err(SignatureError::SignatureVerificationFailed);
        }
        let r = P521ScalarField::from_limbs(r_limbs);
        let s = P521ScalarField::from_limbs(s_limbs);

        let mut h = [0u8; 64];
        self.hash.do_final_out(&mut h);
        let e = e_from_hash(&h);

        let s_inv = s.invert();
        let u = e.mul(&s_inv);
        let v = r.mul(&s_inv);

        let q = P521JacobianPoint::from_affine(pk.x, pk.y);
        let u_pub = P521PublicScalar::from_limbs(u.to_limbs());
        let v_pub = P521PublicScalar::from_limbs(v.to_limbs());
        let r1_point = shamir_multiply(&u_pub, &v_pub, &q);

        if r1_point.is_infinity().to_bool() {
            return Err(SignatureError::SignatureVerificationFailed);
        }
        let (x_r1, _) =
            r1_point.to_affine().expect("just checked r1_point is not the point at infinity");
        let r1 = P521ScalarField::from_limbs(x_r1.to_limbs());

        if r1 == r { Ok(()) } else { Err(SignatureError::SignatureVerificationFailed) }
    }
}

/// `true` iff `limbs`, read as a big-endian-decoded integer, is in `[1, n-1]`.
fn in_range(limbs: &[u64; 9]) -> bool {
    if *limbs == [0; 9] {
        return false;
    }
    let (_, borrow) = nat::sub(limbs, &N_LIMBS);
    borrow == 1
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn r_or_s_is_zero_requires_only_one_to_be_zero() {
        let zero = P521ScalarField::ZERO;
        let one = P521ScalarField::ONE;
        assert!(!r_or_s_is_zero(&one, &one));
        assert!(r_or_s_is_zero(&zero, &one));
        assert!(r_or_s_is_zero(&one, &zero));
        assert!(r_or_s_is_zero(&zero, &zero));
    }
}
