//! `ECDSAP384`: FIPS 186-5 §6.4.1 (signature generation, deterministic per §6.3.2/Appendix A.3.3
//! by default) and §6.4.2 (verification), fixed to SHA-384. Identical in shape to
//! [`crate::ecdsa_p256`] -- see that module's docs for the full reasoning (why `e` needs no
//! truncation, why `x_affine_of_signing_point` exists, the `ctx`/ignore-it stance) -- with P-384's
//! types and SHA-384 substituted.

use crate::keys_p384::{
    ECDSAP384PrivateKey, ECDSAP384PublicKey, PK_LEN, SK_LEN, reduce_mod_n_minus_1_plus_one,
};
use crate::rfc6979_p384;
use bouncycastle_core::errors::SignatureError;
use bouncycastle_core::traits::{Hash, RNG, SignatureVerifier, Signer};
use bouncycastle_ec::nat;
use bouncycastle_ec::p384::P384FieldElement;
use bouncycastle_ec::p384_comb::comb_multiply_base_point;
use bouncycastle_ec::p384_point::P384JacobianPoint;
use bouncycastle_ec::p384_scalar::{N_LIMBS, P384PublicScalar, P384Scalar, P384ScalarField};
use bouncycastle_ec::p384_sec1;
use bouncycastle_ec::p384_wnaf::shamir_multiply;
use bouncycastle_sha2::SHA384;
use bouncycastle_utils::secret::Secret;

/// Raw `r || s` signature length: two 48-byte field-width integers.
pub const SIG_LEN: usize = 96;

/// Upper bound on a DER-encoded P-384 signature (`r`, `s` each 48 bytes); see [`crate::der::max_len`].
pub const DER_SIG_MAX_LEN: usize = crate::der::max_len(48);

/// Streaming state for both `ECDSAP384`'s [`Signer`] and [`SignatureVerifier`] impls. See
/// [`crate::ecdsa_p256::ECDSAP256`]'s docs.
pub struct ECDSAP384 {
    hash: SHA384,
    sk: Option<ECDSAP384PrivateKey>,
    pk: Option<ECDSAP384PublicKey>,
}

/// `x * z^-2`, branch-free. See [`crate::ecdsa_p256::x_affine_of_signing_point`]'s docs.
fn x_affine_of_signing_point(point: &P384JacobianPoint) -> P384FieldElement {
    let z_inv = point.z.invert();
    point.x.mul(&z_inv.mul(&z_inv))
}

/// FIPS 186-5 §6.4.1 steps 4-12, given `k` already generated (step 3).
fn sign_with_k(
    sk: &ECDSAP384PrivateKey,
    e: &P384ScalarField,
    k: P384Scalar,
) -> Result<[u8; SIG_LEN], SignatureError> {
    let k_field = P384ScalarField::from_secret(&k);
    let k_inv = k_field.invert(); // step 4

    let r_point = comb_multiply_base_point(&k); // step 5
    let x_r = x_affine_of_signing_point(&r_point); // steps 6-7
    let r = P384ScalarField::from_limbs(x_r.to_limbs()); // step 8

    let d_field = P384ScalarField::from_secret(sk.scalar());
    let s = k_inv.mul(&e.add(&r.mul(&d_field))); // step 9

    if r_or_s_is_zero(&r, &s) {
        return Err(SignatureError::GenericError(
            "ECDSA signature generation produced r = 0 or s = 0; regenerate k and retry",
        ));
    }

    let mut sig = [0u8; SIG_LEN];
    sig[..48].copy_from_slice(&p384_sec1::be_bytes_from_limbs(&r.to_limbs()));
    sig[48..].copy_from_slice(&p384_sec1::be_bytes_from_limbs(&s.to_limbs()));
    Ok(sig)
}

/// `e` from a 48-byte message hash: `E = H` (no truncation needed, `len(n) == hashlen`), then
/// Appendix B.2.1's big-endian conversion.
fn e_from_hash(h: &[u8; 48]) -> P384ScalarField {
    P384ScalarField::from_limbs(p384_sec1::limbs_from_be_bytes(h))
}

/// FIPS 186-5 §6.4.1 step 11's `r = 0` or `s = 0` check. See
/// [`crate::ecdsa_p256::r_or_s_is_zero`]'s docs.
fn r_or_s_is_zero(r: &P384ScalarField, s: &P384ScalarField) -> bool {
    *r == P384ScalarField::ZERO || *s == P384ScalarField::ZERO
}

impl ECDSAP384 {
    /// FIPS 186-5 §6.4.1 with `k` generated by Appendix A.3.1 ("extra random bits") instead of the
    /// deterministic default. See [`crate::ecdsa_p256::ECDSAP256::sign_randomized`]'s docs. P-384
    /// needs no bits beyond `n`'s own width (see [`crate::keys_p384`]'s docs), so this reduces mod
    /// `n-1` and adds `1` directly rather than going through [`crate::extra_bits`].
    pub fn sign_randomized(
        sk: &ECDSAP384PrivateKey,
        msg: &[u8],
        rng: &mut dyn RNG,
    ) -> Result<[u8; SIG_LEN], SignatureError> {
        let h: [u8; 48] = SHA384::default().hash(msg)[..48].try_into().unwrap();
        let e = e_from_hash(&h);

        // Raw DRBG output, reduced below into the private key / per-message secret: held in
        // `Secret` so it is scrubbed when this function returns rather than left on the stack.
        let mut bytes = Secret::<[u8; SK_LEN]>::new();
        rng.next_bytes_out(&mut *bytes).map_err(SignatureError::RNGError)?;
        let k = reduce_mod_n_minus_1_plus_one(p384_sec1::limbs_from_be_bytes(&bytes));

        sign_with_k(sk, &e, k)
    }

    /// As [`Signer::sign`], but DER-encodes the result. See
    /// [`crate::ecdsa_p256::ECDSAP256::sign_der`]'s docs.
    pub fn sign_der(
        sk: &ECDSAP384PrivateKey,
        msg: &[u8],
        ctx: Option<&[u8]>,
    ) -> Result<([u8; DER_SIG_MAX_LEN], usize), SignatureError> {
        let raw = Self::sign(sk, msg, ctx)?;
        let mut out = [0u8; DER_SIG_MAX_LEN];
        let len = crate::der::encode(&raw[..48], &raw[48..], &mut out);
        Ok((out, len))
    }

    /// As [`SignatureVerifier::verify`], but expects a DER-encoded signature. See
    /// [`crate::ecdsa_p256::ECDSAP256::verify_der`]'s docs.
    pub fn verify_der(
        pk: &ECDSAP384PublicKey,
        msg: &[u8],
        ctx: Option<&[u8]>,
        sig: &[u8],
    ) -> Result<(), SignatureError> {
        let mut raw = [0u8; SIG_LEN];
        let (r_out, s_out) = raw.split_at_mut(48);
        crate::der::decode(sig, r_out, s_out).ok_or(SignatureError::SignatureVerificationFailed)?;
        Self::verify(pk, msg, ctx, &raw)
    }
}

impl Signer<ECDSAP384PrivateKey, SK_LEN, SIG_LEN> for ECDSAP384 {
    fn sign(
        sk: &ECDSAP384PrivateKey,
        msg: &[u8],
        ctx: Option<&[u8]>,
    ) -> Result<[u8; SIG_LEN], SignatureError> {
        let mut s = Self::sign_init(sk, ctx)?;
        s.sign_update(msg);
        s.sign_final()
    }

    fn sign_out(
        sk: &ECDSAP384PrivateKey,
        msg: &[u8],
        ctx: Option<&[u8]>,
        output: &mut [u8; SIG_LEN],
    ) -> Result<usize, SignatureError> {
        output.fill(0);
        *output = Self::sign(sk, msg, ctx)?;
        Ok(SIG_LEN)
    }

    fn sign_init(sk: &ECDSAP384PrivateKey, _ctx: Option<&[u8]>) -> Result<Self, SignatureError> {
        Ok(Self { hash: SHA384::default(), sk: Some(sk.clone()), pk: None })
    }

    fn sign_update(&mut self, msg_chunk: &[u8]) {
        self.hash.do_update(msg_chunk);
    }

    fn sign_final(self) -> Result<[u8; SIG_LEN], SignatureError> {
        let sk = self.sk.ok_or(SignatureError::GenericError(
            "sign_final called on a verify-initialized ECDSAP384; call verify_final instead",
        ))?;
        let mut h = [0u8; 48];
        self.hash.do_final_out(&mut h);
        let e = e_from_hash(&h);
        let k = rfc6979_p384::generate_k(sk.scalar(), &h);
        sign_with_k(&sk, &e, k)
    }

    fn sign_final_out(self, output: &mut [u8; SIG_LEN]) -> Result<usize, SignatureError> {
        output.fill(0);
        *output = self.sign_final()?;
        Ok(SIG_LEN)
    }
}

impl SignatureVerifier<ECDSAP384PublicKey, PK_LEN, SIG_LEN> for ECDSAP384 {
    fn verify(
        pk: &ECDSAP384PublicKey,
        msg: &[u8],
        ctx: Option<&[u8]>,
        sig: &[u8],
    ) -> Result<(), SignatureError> {
        let mut v = Self::verify_init(pk, ctx)?;
        v.verify_update(msg);
        v.verify_final(sig)
    }

    fn verify_init(pk: &ECDSAP384PublicKey, _ctx: Option<&[u8]>) -> Result<Self, SignatureError> {
        Ok(Self { hash: SHA384::default(), sk: None, pk: Some(*pk) })
    }

    fn verify_update(&mut self, msg_chunk: &[u8]) {
        self.hash.do_update(msg_chunk);
    }

    fn verify_final(self, sig: &[u8]) -> Result<(), SignatureError> {
        let pk = self.pk.ok_or(SignatureError::GenericError(
            "verify_final called on a sign-initialized ECDSAP384; call sign_final instead",
        ))?;
        // Exactly SIG_LEN, not "at least": the raw encoding is two fixed-width integers and
        // nothing else, so trailing bytes make this a different, malformed encoding rather than a
        // valid signature in a roomy buffer. Accepting them would let anyone turn one valid
        // signature into unlimited distinct byte strings that all verify -- malleability that
        // breaks any caller treating the signature as an opaque, comparable blob. This matches how
        // `SignaturePublicKey`/`SignaturePrivateKey::from_bytes` already reject an over-long
        // encoding here (see `core-test-framework`'s own `test_boundary_conditions`).
        if sig.len() != SIG_LEN {
            return Err(SignatureError::SignatureVerificationFailed);
        }

        let r_limbs = p384_sec1::limbs_from_be_bytes(&sig[..48].try_into().unwrap());
        let s_limbs = p384_sec1::limbs_from_be_bytes(&sig[48..96].try_into().unwrap());
        if !in_range(&r_limbs) || !in_range(&s_limbs) {
            return Err(SignatureError::SignatureVerificationFailed);
        }
        let r = P384ScalarField::from_limbs(r_limbs);
        let s = P384ScalarField::from_limbs(s_limbs);

        let mut h = [0u8; 48];
        self.hash.do_final_out(&mut h);
        let e = e_from_hash(&h);

        let s_inv = s.invert();
        let u = e.mul(&s_inv);
        let v = r.mul(&s_inv);

        let q = P384JacobianPoint::from_affine(pk.x, pk.y);
        let u_pub = P384PublicScalar::from_limbs(u.to_limbs());
        let v_pub = P384PublicScalar::from_limbs(v.to_limbs());
        let r1_point = shamir_multiply(&u_pub, &v_pub, &q);

        if r1_point.is_infinity().to_bool() {
            return Err(SignatureError::SignatureVerificationFailed);
        }
        let (x_r1, _) =
            r1_point.to_affine().expect("just checked r1_point is not the point at infinity");
        let r1 = P384ScalarField::from_limbs(x_r1.to_limbs());

        if r1 == r { Ok(()) } else { Err(SignatureError::SignatureVerificationFailed) }
    }
}

/// `true` iff `limbs`, read as a big-endian-decoded integer, is in `[1, n-1]`.
fn in_range(limbs: &[u64; 6]) -> bool {
    if *limbs == [0, 0, 0, 0, 0, 0] {
        return false;
    }
    let (_, borrow) = nat::sub(limbs, &N_LIMBS);
    borrow == 1
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn r_or_s_is_zero_requires_only_one_to_be_zero() {
        let zero = P384ScalarField::ZERO;
        let one = P384ScalarField::ONE;
        assert!(!r_or_s_is_zero(&one, &one));
        assert!(r_or_s_is_zero(&zero, &one));
        assert!(r_or_s_is_zero(&one, &zero));
        assert!(r_or_s_is_zero(&zero, &zero));
    }
}
