//! Ascon-AEAD128 authenticated encryption, as specified in NIST SP 800-232 §4.
//!
//! Rate = 128 bits, capacity = 192 bits, 128-bit key/nonce/tag. Initialization and finalization use
//! `Ascon-p[12]`; associated-data and plaintext/ciphertext blocks use `Ascon-p[8]`.
//!
//! [`Ascon_AEAD128`] is used through [`AEADCipherEncryptor`] / [`AEADCipherDecryptor`], with
//! `FINAL_LEN = TAG_LEN`, and through the [`SymmetricCipherEncryptor`] /
//! [`SymmetricCipherDecryptor`] traits they extend, in the same shape as
//! `bouncycastle_cipher::modes::Gcm`: the direction is the type parameter, [`Encrypting`] or
//! [`Decrypting`], and the nonce is generated by `do_encrypt_init` / `do_encrypt_init_rng` and
//! returned, never supplied. See the crate docs for examples.

use core::fmt::{self, Debug, Display, Formatter};
use core::marker::PhantomData;

use bouncycastle_cipher::{Decrypting, Encrypting};
use bouncycastle_core::errors::{KeyMaterialError, SuspendableError, SymmetricCipherError};
use bouncycastle_core::key_material::{KeyMaterial, KeyMaterialTrait, KeyType};
use bouncycastle_core::security_strength::SecurityStrength;
use bouncycastle_core::traits::{
    AEADCipherDecryptor, AEADCipherEncryptor, Algorithm, RNG, SuspendableKeyed,
    SymmetricCipherDecryptor, SymmetricCipherEncryptor,
};
use bouncycastle_rng::HashDRBG_SHA512;
use bouncycastle_utils::ct::ct_eq_bytes;
use bouncycastle_utils::secret::Secret;
use bouncycastle_utils::suspendable_state::{add_lib_ver, check_lib_ver};

use crate::ASCON_AEAD128_NAME;
use crate::permutation::{AsconState, load_u64_le, p8, p12, store_u64_le};

/// Length in bytes of the Ascon-AEAD128 key.
pub const KEY_LEN: usize = 16;
/// Length in bytes of the Ascon-AEAD128 nonce.
pub const NONCE_LEN: usize = 16;
/// Length in bytes of the Ascon-AEAD128 authentication tag.
pub const TAG_LEN: usize = 16;
const RATE: usize = 16;

/// Ascon-AEAD128 initial value (SP 800-232 Table 14).
const ASCON_IV: u64 = 0x00001000808C0001;

/// Which category of bytes the state is absorbing. Three phases rather than GCM's two because
/// SP 800-232 §4.1.1 step 2 processes the associated data only "if the AD is non-empty
/// (i.e., |A| > 0)": the AAD padding block is absorbed on the `Aad` -> `Data` transition and
/// skipped on `Init` -> `Data`, so whether any AAD was ever seen has to be remembered.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Phase {
    /// Nothing absorbed since initialization.
    Init = 0,
    /// At least one byte of AAD absorbed.
    Aad = 1,
    /// Plaintext/ciphertext has started; AAD is no longer accepted.
    Data = 2,
}

impl Phase {
    /// The inverse of `as u8`, for a suspended state; anything but the three values is refused.
    fn from_u8(v: u8) -> Result<Self, SuspendableError> {
        match v {
            0 => Ok(Phase::Init),
            1 => Ok(Phase::Aad),
            2 => Ok(Phase::Data),
            _ => Err(SuspendableError::InvalidData),
        }
    }
}

/// Ascon-AEAD128 (NIST SP 800-232), spelled as the specification spells it, direction typed as
/// [`Encrypting`] / [`Decrypting`]. The wrong direction is a compile error, not a runtime check,
/// and the nonce is generated by encryption and returned, never supplied.
///
/// Both directions implement [`AEADCipherEncryptor`] / [`AEADCipherDecryptor`] and, through them,
/// [`SymmetricCipherEncryptor`] / [`SymmetricCipherDecryptor`] -- which is the AEAD with no
/// associated data and the tag inline:
///
/// ```
/// use bouncycastle_ascon::Ascon_AEAD128;
/// use bouncycastle_core::key_material::{KeyMaterial, KeyType};
/// use bouncycastle_cipher::{Decrypting, Encrypting};
/// use bouncycastle_core::traits::{SymmetricCipherDecryptor, SymmetricCipherEncryptor};
///
/// type Enc = Ascon_AEAD128<Encrypting>;
/// type Dec = Ascon_AEAD128<Decrypting>;
///
/// let key = KeyMaterial::<16>::from_bytes_as_type(&[0x42; 16], KeyType::SymmetricCipherKey)
///     .expect("a 16-byte symmetric cipher key");
///
/// let message = b"hello";
/// let mut ciphertext = [0u8; 5 + 16]; // Enc::encrypt_out_len(5): ciphertext || tag
/// let (nonce, written) = Enc::encrypt_out(&key, message, &mut ciphertext).expect("encryption");
/// assert_eq!(written, 21);
///
/// let mut plaintext = [0u8; 5]; // Dec::decrypt_out_len(21)
/// let n = Dec::decrypt_out(&key, &nonce, &ciphertext, &mut plaintext).expect("decryption");
/// assert_eq!(&plaintext[..n], message);
/// ```
///
/// `FINAL_LEN` is `TAG_LEN`: the encryptor holds nothing back, so its inline
/// [`SymmetricCipherEncryptor::do_encrypt_final`] is exactly the tag and its detached
/// [`AEADCipherEncryptor::do_encrypt_final_detachedtag_out`] flushes nothing. The decryptor holds
/// back the last `TAG_LEN` bytes it has seen, since until the stream ends they may be the inline
/// tag; [`AEADCipherDecryptor::do_decrypt_final_detachedtag_out`] releases them as ciphertext.
#[allow(non_camel_case_types)]
#[derive(Clone)]
pub struct Ascon_AEAD128<Dir> {
    // 128-bit secret key (two 64-bit words). It is re-added to the state at finalization, so it must
    // be retained; wrapped in `Secret` for volatile-write zeroization on drop.
    key: Secret<[u64; 2]>,
    // 320-bit internal state (five 64-bit words). Carries keystream/plaintext-derived material, so
    // it is likewise wrapped in `Secret`.
    state: Secret<AsconState>,
    // Byte position (0..RATE) within the current rate block.
    pos: usize,
    phase: Phase,
    // The last up to `TAG_LEN` bytes of ciphertext seen by `do_decrypt_out` but not yet absorbed,
    // because they might be the inline tag. Meaningful only on the `Decrypting` side; kept on both
    // directions rather than splitting the struct by `Dir`, as `Gcm` does. Ciphertext, not
    // plaintext, so no `Secret` wrapper.
    tail: [u8; TAG_LEN],
    // How many bytes of `tail` are meaningful, always `min(TAG_LEN, total ciphertext seen)`.
    tail_len: usize,
    _dir: PhantomData<Dir>,
}

impl<Dir> Ascon_AEAD128<Dir> {
    /// Validate a [`KeyMaterial`] for use with Ascon-AEAD128 and return its key words.
    /// The key must be tagged as a [`KeyType::SymmetricCipherKey`] and carry at least the
    /// algorithm's 128-bit security strength (SP 800-232 R1/R2).
    fn checked_key(key: &KeyMaterial<KEY_LEN>) -> Result<[u64; 2], SymmetricCipherError> {
        if key.key_type() != KeyType::SymmetricCipherKey {
            return Err(KeyMaterialError::InvalidKeyType(
                "Ascon-AEAD128 requires a SymmetricCipherKey",
            )
            .into());
        }
        if key.security_strength() < SecurityStrength::_128bit {
            return Err(KeyMaterialError::SecurityStrength(
                "Ascon-AEAD128 requires a key with at least 128-bit security strength",
            )
            .into());
        }
        let bytes = key.ref_to_bytes();
        if bytes.len() != KEY_LEN {
            return Err(KeyMaterialError::InvalidLength.into());
        }
        Ok([load_u64_le(bytes, 0), load_u64_le(bytes, 8)])
    }

    /// Initialization (SP 800-232 §4.1.1 step 1 / Eq. 15-17): S = IV||K||N, then Ascon-p[12],
    /// then XOR K into the last 128 bits. The body of both directions' `do_*_init`.
    fn setup(
        key: &KeyMaterial<KEY_LEN>,
        nonce: &[u8; NONCE_LEN],
    ) -> Result<Self, SymmetricCipherError> {
        let key_words = Self::checked_key(key)?;
        let mut key_secret: Secret<[u64; 2]> = Secret::new();
        *key_secret = key_words;

        let mut state: Secret<AsconState> = Secret::new();
        state[0] = ASCON_IV;
        state[1] = key_words[0];
        state[2] = key_words[1];
        state[3] = load_u64_le(nonce, 0);
        state[4] = load_u64_le(nonce, 8);
        p12(&mut state);
        state[3] ^= key_words[0];
        state[4] ^= key_words[1];

        Ok(Self {
            key: key_secret,
            state,
            pos: 0,
            phase: Phase::Init,
            tail: [0u8; TAG_LEN],
            tail_len: 0,
            _dir: PhantomData,
        })
    }

    /// Read the value of state byte `pos` (0 = LSB of word 0, ..., 15 = MSB of word 1).
    fn state_byte(&self, pos: usize) -> u8 {
        let word = if pos < 8 { self.state[0] } else { self.state[1] };
        (word >> ((pos % 8) * 8)) as u8
    }

    /// XOR `b` into state byte `pos`.
    fn xor_state_byte(&mut self, pos: usize, b: u8) {
        let shifted = (b as u64) << ((pos % 8) * 8);
        if pos < 8 { self.state[0] ^= shifted } else { self.state[1] ^= shifted }
    }

    /// Overwrite state byte `pos` with `b`.
    fn set_state_byte(&mut self, pos: usize, b: u8) {
        let shift = (pos % 8) * 8;
        let mask = !(0xFFu64 << shift);
        let shifted = (b as u64) << shift;
        if pos < 8 {
            self.state[0] = (self.state[0] & mask) | shifted;
        } else {
            self.state[1] = (self.state[1] & mask) | shifted;
        }
    }

    /// Advance to the next byte position, running `Ascon-p[8]` and wrapping back to 0 once a full
    /// rate block (16 bytes) has been absorbed.
    fn advance(&mut self) {
        self.pos += 1;
        if self.pos == RATE {
            p8(&mut self.state);
            self.pos = 0;
        }
    }

    /// Absorbs associated data (SP 800-232 §4.1.1 step 2): the body of both directions'
    /// `AEADCipher*::do_update_aad`. Any number of calls before the first data; a non-empty call
    /// after data has started is [`SymmetricCipherError::StateError`]. Empty AAD is always a no-op.
    fn absorb_aad(&mut self, aad: &[u8]) -> Result<(), SymmetricCipherError> {
        if aad.is_empty() {
            return Ok(());
        }
        match self.phase {
            Phase::Init => self.phase = Phase::Aad,
            Phase::Aad => {}
            Phase::Data => {
                return Err(SymmetricCipherError::StateError(
                    "Ascon-AEAD128: associated data must be processed before plaintext/ciphertext",
                ));
            }
        }

        let mut aad = aad;
        while !aad.is_empty() {
            if self.pos == 0 && aad.len() >= RATE {
                self.state[0] ^= load_u64_le(aad, 0);
                self.state[1] ^= load_u64_le(aad, 8);
                p8(&mut self.state);
                aad = &aad[RATE..];
            } else {
                self.xor_state_byte(self.pos, aad[0]);
                self.advance();
                aad = &aad[1..];
            }
        }
        Ok(())
    }

    /// The AAD-to-data transition, the first time data arrives; a no-op on every later call.
    /// Pads and absorbs the final (possibly empty) AAD block only if any AAD was supplied
    /// (§4.1.1 step 2 is skipped when |A| = 0), then applies the domain-separation bit
    /// unconditionally (Eq. 22/40: S ^= 0^319 || 1).
    fn begin_data_if_needed(&mut self) {
        match self.phase {
            Phase::Data => return,
            Phase::Aad => {
                self.xor_state_byte(self.pos, 0x01);
                p8(&mut self.state);
                self.pos = 0;
            }
            Phase::Init => {}
        }
        self.state[4] ^= 0x8000000000000000;
        self.phase = Phase::Data;
    }

    /// Finalization, shared by both directions: pads the final (possibly empty) data block
    /// (Eq. 27/47), then §4.1.1 step 4 / §4.1.2 step 4 (Eq. 30-32 / 49-51): re-add the key,
    /// permute with Ascon-p[12], and add the key again; the tag is the resulting last 128 bits.
    fn finish(mut self) -> [u8; TAG_LEN] {
        self.begin_data_if_needed();
        self.xor_state_byte(self.pos, 0x01);

        self.state[2] ^= self.key[0];
        self.state[3] ^= self.key[1];
        p12(&mut self.state);
        self.state[3] ^= self.key[0];
        self.state[4] ^= self.key[1];

        let mut tag = [0u8; TAG_LEN];
        store_u64_le(&mut tag, 0, self.state[3]);
        store_u64_le(&mut tag, 8, self.state[4]);
        tag
    }
}

impl<Dir> Algorithm for Ascon_AEAD128<Dir> {
    const ALG_NAME: &'static str = ASCON_AEAD128_NAME;
    const MAX_SECURITY_STRENGTH: SecurityStrength = SecurityStrength::_128bit;
}

impl Ascon_AEAD128<Encrypting> {
    /// Encrypts `data` in place (SP 800-232 §4.1.1 step 3). Every byte is transformed as soon as
    /// it is seen: within a rate block each byte is independent of the others, and the
    /// permutation runs only once a full 16-byte block has been absorbed, so nothing is held back.
    fn encrypt_in_place(&mut self, data: &mut [u8]) {
        self.begin_data_if_needed();

        let mut data = data;
        while !data.is_empty() {
            if self.pos == 0 && data.len() >= RATE {
                let c0 = self.state[0] ^ load_u64_le(data, 0);
                let c1 = self.state[1] ^ load_u64_le(data, 8);
                store_u64_le(data, 0, c0);
                store_u64_le(data, 8, c1);
                self.state[0] = c0;
                self.state[1] = c1;
                p8(&mut self.state);
                data = &mut data[RATE..];
            } else {
                self.xor_state_byte(self.pos, data[0]);
                data[0] = self.state_byte(self.pos);
                self.advance();
                data = &mut data[1..];
            }
        }
    }
}

impl SymmetricCipherEncryptor<KEY_LEN, NONCE_LEN, TAG_LEN> for Ascon_AEAD128<Encrypting> {
    fn do_encrypt_init(
        key: &KeyMaterial<KEY_LEN>,
    ) -> Result<(Self, [u8; NONCE_LEN]), SymmetricCipherError> {
        let mut rng = HashDRBG_SHA512::new_from_os();
        Self::do_encrypt_init_rng(key, &mut rng)
    }

    fn do_encrypt_init_rng(
        key: &KeyMaterial<KEY_LEN>,
        rng: &mut dyn RNG,
    ) -> Result<(Self, [u8; NONCE_LEN]), SymmetricCipherError> {
        let mut nonce = [0u8; NONCE_LEN];
        rng.next_bytes_out(&mut nonce)?;
        Ok((Self::setup(key, &nonce)?, nonce))
    }

    /// The identity: the encryptor holds nothing back.
    fn do_encrypt_out_len(&self, input_len: usize) -> usize {
        input_len
    }

    fn do_encrypt_out(
        &mut self,
        plaintext: &[u8],
        ciphertext: &mut [u8],
    ) -> Result<usize, SymmetricCipherError> {
        ciphertext.fill(0);
        if ciphertext.len() < plaintext.len() {
            return Err(SymmetricCipherError::OutputBufferTooSmall(plaintext.len()));
        }
        let out = &mut ciphertext[..plaintext.len()];
        out.copy_from_slice(plaintext);
        self.encrypt_in_place(out);
        Ok(plaintext.len())
    }

    /// The inline layout: nothing is held back, so the final buffer is exactly the tag.
    fn do_encrypt_final(self) -> Result<([u8; TAG_LEN], usize), SymmetricCipherError> {
        Ok((self.finish(), TAG_LEN))
    }

    /// The ciphertext, which is as long as the plaintext, followed by the tag.
    fn encrypt_out_len(plaintext_len: usize) -> usize {
        plaintext_len + TAG_LEN
    }
}

impl AEADCipherEncryptor<KEY_LEN, NONCE_LEN, TAG_LEN, TAG_LEN> for Ascon_AEAD128<Encrypting> {
    fn do_update_aad(&mut self, aad: &[u8]) -> Result<(), SymmetricCipherError> {
        self.absorb_aad(aad)
    }

    /// Nothing is ever held back to flush, so `ciphertext` is left zeroed.
    fn do_encrypt_final_detachedtag_out(
        self,
        ciphertext: &mut [u8; TAG_LEN],
    ) -> Result<(usize, [u8; TAG_LEN]), SymmetricCipherError> {
        ciphertext.fill(0);
        Ok((0, self.finish()))
    }
}

impl Ascon_AEAD128<Decrypting> {
    /// Decrypts `data` in place (SP 800-232 §4.1.2 step 3), the mirror of `encrypt_in_place`:
    /// the ciphertext replaces the rate bytes rather than being XORed in. The plaintext this
    /// releases is **not yet authenticated**; see the crate docs' Security Considerations.
    fn decrypt_in_place(&mut self, data: &mut [u8]) {
        self.begin_data_if_needed();

        let mut data = data;
        while !data.is_empty() {
            if self.pos == 0 && data.len() >= RATE {
                let t0 = load_u64_le(data, 0);
                let t1 = load_u64_le(data, 8);
                store_u64_le(data, 0, self.state[0] ^ t0);
                store_u64_le(data, 8, self.state[1] ^ t1);
                self.state[0] = t0;
                self.state[1] = t1;
                p8(&mut self.state);
                data = &mut data[RATE..];
            } else {
                let c = data[0];
                data[0] = self.state_byte(self.pos) ^ c;
                self.set_state_byte(self.pos, c);
                self.advance();
                data = &mut data[1..];
            }
        }
    }

    /// Finalization (§4.1.2 step 4): computes the tag and compares it against `tag` in constant
    /// time.
    fn verify(self, tag: &[u8; TAG_LEN]) -> Result<(), SymmetricCipherError> {
        let computed = self.finish();
        if !ct_eq_bytes(&computed, tag) {
            return Err(SymmetricCipherError::AEADTagCheckFailed);
        }
        Ok(())
    }
}

impl SymmetricCipherDecryptor<KEY_LEN, NONCE_LEN, TAG_LEN> for Ascon_AEAD128<Decrypting> {
    fn do_decrypt_init(
        key: &KeyMaterial<KEY_LEN>,
        nonce: &[u8; NONCE_LEN],
    ) -> Result<Self, SymmetricCipherError> {
        Self::setup(key, nonce)
    }

    /// Everything but the last `TAG_LEN` bytes seen so far is released.
    fn do_decrypt_out_len(&self, input_len: usize) -> usize {
        (self.tail_len + input_len).saturating_sub(TAG_LEN)
    }

    fn do_decrypt_out(
        &mut self,
        ciphertext: &[u8],
        plaintext: &mut [u8],
    ) -> Result<usize, SymmetricCipherError> {
        plaintext.fill(0);
        let release = self.do_decrypt_out_len(ciphertext.len());
        if plaintext.len() < release {
            return Err(SymmetricCipherError::OutputBufferTooSmall(release));
        }
        // The oldest bytes go first: the held-back ones, then the front of `ciphertext`.
        let from_tail = release.min(self.tail_len);
        let from_input = release - from_tail;
        let out = &mut plaintext[..release];
        out[..from_tail].copy_from_slice(&self.tail[..from_tail]);
        out[from_tail..].copy_from_slice(&ciphertext[..from_input]);
        // Called even when `release` is 0: that is what ends the AAD phase, so a later non-empty
        // `do_update_aad` is refused however little ciphertext has been seen.
        self.decrypt_in_place(out);
        // Keep the newest `TAG_LEN` (or fewer) bytes: what is left of `tail`, then the end of
        // `ciphertext`.
        let kept = self.tail_len - from_tail;
        self.tail.copy_within(from_tail..self.tail_len, 0);
        let new_len = kept + ciphertext.len() - from_input;
        self.tail[kept..new_len].copy_from_slice(&ciphertext[from_input..]);
        self.tail_len = new_len;
        Ok(release)
    }

    /// The inline layout: the held-back bytes are the tag, so there is no plaintext left to
    /// release.
    ///
    /// # Errors
    /// [`SymmetricCipherError::DecryptionFailed`] if fewer than `TAG_LEN` bytes were seen in all;
    /// [`SymmetricCipherError::AEADTagCheckFailed`] if the tag does not verify.
    fn do_decrypt_final(self) -> Result<([u8; TAG_LEN], usize), SymmetricCipherError> {
        if self.tail_len < TAG_LEN {
            return Err(SymmetricCipherError::DecryptionFailed);
        }
        let tag = self.tail;
        self.verify(&tag)?;
        Ok(([0u8; TAG_LEN], 0))
    }

    /// Everything but the trailing tag.
    fn decrypt_out_len(ciphertext_len: usize) -> usize {
        ciphertext_len.saturating_sub(TAG_LEN)
    }
}

impl AEADCipherDecryptor<KEY_LEN, NONCE_LEN, TAG_LEN, TAG_LEN> for Ascon_AEAD128<Decrypting> {
    fn do_update_aad(&mut self, aad: &[u8]) -> Result<(), SymmetricCipherError> {
        self.absorb_aad(aad)
    }

    /// The detached layout: the held-back bytes are ciphertext after all, so they are decrypted
    /// into `plaintext` before the tag is checked against `tag`. On a failed check `plaintext` is
    /// zeroized, so the error leaves nothing unauthenticated behind in it (what earlier
    /// `do_decrypt_out` calls released is the caller's to scrub).
    fn do_decrypt_final_detachedtag_out(
        mut self,
        tag: &[u8; TAG_LEN],
        plaintext: &mut [u8; TAG_LEN],
    ) -> Result<usize, SymmetricCipherError> {
        plaintext.fill(0);
        let n = self.tail_len;
        plaintext[..n].copy_from_slice(&self.tail[..n]);
        self.decrypt_in_place(&mut plaintext[..n]);
        if let Err(e) = self.verify(tag) {
            plaintext.fill(0);
            return Err(e);
        }
        Ok(n)
    }
}

impl<Dir> Debug for Ascon_AEAD128<Dir> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        write!(f, "Ascon_AEAD128 (key/state masked)")
    }
}

impl<Dir> Display for Ascon_AEAD128<Dir> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        write!(f, "Ascon_AEAD128 (key/state masked)")
    }
}

/// Length in bytes of the serialized state of [`Ascon_AEAD128`].
/// Layout: 3-byte library version || 1-byte state tag || 40-byte permutation state (5 × u64 LE)
/// || 1-byte byte position within the current rate block || 1-byte phase || 16-byte held-back
/// tail || 1-byte tail length.
/// The secret key is **not** serialized; it is re-supplied to [`SuspendableKeyed::from_suspended`].
/// The direction is not serialized either: it is the type the state is resumed into.
pub const SUSPENDED_ASCON_AEAD128_STATE_LEN: usize = 63;

const AEAD128_STATE_TAG: u8 = 0x04;

// Offsets within the state, after the 3-byte version prefix.
const STATE_OFFSET: usize = 1;
const POS_OFFSET: usize = STATE_OFFSET + 40;
const PHASE_OFFSET: usize = POS_OFFSET + 1;
const TAIL_OFFSET: usize = PHASE_OFFSET + 1;
const TAIL_LEN_OFFSET: usize = TAIL_OFFSET + TAG_LEN;
const _: () = assert!(TAIL_LEN_OFFSET + 1 == SUSPENDED_ASCON_AEAD128_STATE_LEN - 3);

impl<Dir> SuspendableKeyed<SUSPENDED_ASCON_AEAD128_STATE_LEN> for Ascon_AEAD128<Dir> {
    // The 128-bit key must be re-supplied when resuming; it is never part of the serialized state,
    // and is re-validated exactly as the constructors validate it.
    type Key = KeyMaterial<KEY_LEN>;

    fn suspend(self) -> [u8; SUSPENDED_ASCON_AEAD128_STATE_LEN] {
        let mut out_to_return = [0u8; SUSPENDED_ASCON_AEAD128_STATE_LEN];
        // infallible: add_lib_ver returns a slice of exactly SUSPENDED_ASCON_AEAD128_STATE_LEN - 3 = 60 bytes.
        let out: &mut [u8; SUSPENDED_ASCON_AEAD128_STATE_LEN - 3] =
            add_lib_ver(&mut out_to_return).try_into().unwrap();

        out[0] = AEAD128_STATE_TAG;
        for i in 0..5 {
            out[STATE_OFFSET + i * 8..STATE_OFFSET + i * 8 + 8]
                .copy_from_slice(&self.state[i].to_le_bytes());
        }
        debug_assert!(self.pos < RATE);
        out[POS_OFFSET] = self.pos as u8;
        out[PHASE_OFFSET] = self.phase as u8;
        out[TAIL_OFFSET..TAIL_LEN_OFFSET].copy_from_slice(&self.tail);
        debug_assert!(self.tail_len <= TAG_LEN);
        out[TAIL_LEN_OFFSET] = self.tail_len as u8;

        out_to_return
    }

    fn from_suspended(
        serialized_state: [u8; SUSPENDED_ASCON_AEAD128_STATE_LEN],
        key: &Self::Key,
    ) -> Result<Self, SuspendableError> {
        // infallible: check_lib_ver returns a slice of exactly SUSPENDED_ASCON_AEAD128_STATE_LEN - 3 = 60 bytes.
        let input: &[u8; SUSPENDED_ASCON_AEAD128_STATE_LEN - 3] =
            check_lib_ver(&serialized_state, None)?.try_into().unwrap();

        if input[0] != AEAD128_STATE_TAG {
            return Err(SuspendableError::InvalidData);
        }
        let mut state = Secret::<AsconState>::new();
        for i in 0..5 {
            // infallible: each slice is exactly 8 bytes by construction.
            state[i] = u64::from_le_bytes(
                input[STATE_OFFSET + i * 8..STATE_OFFSET + i * 8 + 8].try_into().unwrap(),
            );
        }
        let pos = input[POS_OFFSET] as usize;
        if pos >= RATE {
            return Err(SuspendableError::InvalidData);
        }
        let phase = Phase::from_u8(input[PHASE_OFFSET])?;
        // A nonzero byte position means at least one AAD/data byte has been absorbed into the
        // current rate block, which is impossible while still in `Init`.
        if pos != 0 && phase == Phase::Init {
            return Err(SuspendableError::InvalidData);
        }
        let mut tail = [0u8; TAG_LEN];
        tail.copy_from_slice(&input[TAIL_OFFSET..TAIL_LEN_OFFSET]);
        let tail_len = input[TAIL_LEN_OFFSET] as usize;
        // The tail is only ever filled by `do_decrypt_out`, which moves the phase to `Data` on
        // its first call, so a held-back tail in any other phase is inconsistent.
        if tail_len > TAG_LEN || (tail_len != 0 && phase != Phase::Data) {
            return Err(SuspendableError::InvalidData);
        }

        let key_words = Self::checked_key(key).map_err(|_| SuspendableError::InvalidData)?;
        let mut key_secret = Secret::<[u64; 2]>::new();
        *key_secret = key_words;

        Ok(Self { key: key_secret, state, pos, phase, tail, tail_len, _dir: PhantomData })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Phase is private, so its `as u8` / from_u8 round trip -- exercised end-to-end via
    // suspend/resume in tests/aead128_tests.rs for the states reachable there -- is pinned
    // directly here for every discriminant, including the two a successful resume never needs to
    // decode into (Init and Aad never survive to be the end state of a still-running cipher in
    // the integration tests, since further processing always advances them to Data).
    #[test]
    fn phase_u8_round_trip() {
        for p in [Phase::Init, Phase::Aad, Phase::Data] {
            assert_eq!(Phase::from_u8(p as u8).unwrap(), p, "round trip failed for {p:?}");
        }
        for v in [3u8, 200] {
            assert!(Phase::from_u8(v).is_err(), "discriminant {v} must be rejected");
        }
    }
}
