#[cfg(test)]
mod hmac_sm3_tests {
    use bouncycastle_core::key_material;
    use bouncycastle_core::key_material::{KeyMaterial256, KeyMaterialTrait, KeyType};
    use bouncycastle_core::traits::{Algorithm, MAC};
    use bouncycastle_core_test_framework::DUMMY_SEED;
    use bouncycastle_core_test_framework::mac::TestFrameworkMAC;
    use bouncycastle_hex as hex;
    use bouncycastle_rng::HashDRBG_SHA512;
    use bouncycastle_sm3::hmac::*;

    /// HMAC-SM3 known answers. There is no RFC 4231 equivalent for SM3, so these reuse the RFC 4231
    /// keys/messages (cases 1, 2 and 6) with expected values generated by
    /// `openssl dgst -sm3 -mac HMAC` and independently confirmed with bc-java's
    /// `HMac(new SM3Digest())`, plus a zero-length key.
    #[test]
    fn hmac_sm3_known_answers() {
        use bouncycastle_core::key_material::KeyMaterial;
        let test_framework = TestFrameworkMAC::new();

        // RFC4231 Test Case 1 key/message
        test_framework.test_mac::<HMAC_SM3>(
            &KeyMaterial::<20>::from_bytes_as_type(
                &hex::decode("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b").unwrap(),
                KeyType::MACKey,
            )
            .unwrap(),
            b"Hi There",
            &hex::decode("51b00d1fb49832bfb01c3ce27848e59f871d9ba938dc563b338ca964755cce70")
                .unwrap(),
        );
        // RFC4231 Test Case 2 key/message
        test_framework.test_mac::<HMAC_SM3>(
            &KeyMaterial::<4>::from_bytes_as_type(b"Jefe", KeyType::MACKey).unwrap(),
            b"what do ya want for nothing?",
            &hex::decode("2e87f1d16862e6d964b50a5200bf2b10b764faa9680a296a2405f24bec39f882")
                .unwrap(),
        );
        // RFC4231 Test Case 6 key/message: key larger than the 64-byte block, so it is hashed first
        test_framework.test_mac::<HMAC_SM3>(
            &KeyMaterial::<131>::from_bytes_as_type(&[0xaa; 131], KeyType::MACKey).unwrap(),
            b"Test Using Larger Than Block-Size Key - Hash Key First",
            &hex::decode("b4fd844e13342002f0b2e0690ea7741f1497d993a70494cea601e657bedf67a0")
                .unwrap(),
        );

        // zero-length key (weak; needs new_allow_weak_key)
        let mut zero_length_key = KeyMaterial256::default();
        key_material::do_hazardous_operations(&mut zero_length_key, |k| {
            k.set_key_type(KeyType::MACKey)
        })
        .unwrap();
        let mut mac = HMAC_SM3::new_allow_weak_key(&zero_length_key).unwrap();
        mac.do_update(b"abc");
        assert_eq!(
            mac.do_final(),
            hex::decode("36525058ca466791502435c910517f1a7e86613d5f35ac1f18a94def0eaac81f")
                .unwrap()
        );

        assert_eq!(
            HMAC_SM3::new(
                &KeyMaterial256::from_bytes_as_type(&DUMMY_SEED[..32], KeyType::MACKey).unwrap()
            )
            .unwrap()
            .output_len(),
            32
        );
    }

    #[test]
    fn algorithm_tests() {
        assert_eq!(HMAC_SM3::ALG_NAME, HMAC_SM3_NAME);
    }

    #[test]
    fn suspendable_keyed_state() {
        use bouncycastle_core::errors::SuspendableError;
        use bouncycastle_core::suspendable_state::LIB_VERSION;
        use bouncycastle_core::traits::SuspendableKeyed;
        use bouncycastle_core_test_framework::suspendable_state::TestFrameworkSuspendableKeyedState;

        let key = KeyMaterial256::from_bytes_as_type(&DUMMY_SEED[..32], KeyType::MACKey).unwrap();
        let msg = b"Colorless green ideas sleep furiously";

        // A helper that exercises the full round-trip for one HMAC variant. HMAC is keyed, so the
        // key is NOT in the serialized state -- it is re-supplied (by reference) to
        // from_serialized_state.
        // The `+ 'static` on the trait object matches the associated type `type Key = dyn
        // KeyMaterialTrait` (a bare `dyn` in an associated type defaults to `'static`). The concrete
        // key types are owned, so they satisfy it.
        fn round_trip<const N: usize, H>(
            mut hmac: H,
            key: &(dyn KeyMaterialTrait + 'static),
            input: &[u8],
        ) where
            H: MAC + Clone + SuspendableKeyed<N, Key = dyn KeyMaterialTrait>,
        {
            hmac.do_update(&input[..10]);

            // do the default trait-conformance tests
            TestFrameworkSuspendableKeyedState::new().test(&hmac, key);

            // serialize the in-progress state (on a clone), then finish the original
            let serialized_state = hmac.clone().suspend();

            // the serialized state carries the library version header (from the inner hash)
            let header: [u8; 3] = serialized_state[..3].try_into().unwrap();
            assert_eq!(header, <[u8; 3]>::from(LIB_VERSION));

            hmac.do_update(&input[10..]);
            let expected = hmac.do_final();

            // rebuild from the serialized state (re-supplying the key), feed the identical remaining
            // input, and confirm the MAC matches
            let mut from_state = H::from_suspended(serialized_state, key).unwrap();
            from_state.do_update(&input[10..]);
            assert_eq!(expected, from_state.do_final());

            // a state whose version header is zeroed must be rejected (delegated to the hash's impl)
            let mut busted = serialized_state;
            busted[..3].copy_from_slice(&[0, 0, 0]);
            match H::from_suspended(busted, key) {
                Err(SuspendableError::IncompatibleVersion) => { /* good */ }
                _ => panic!("Expected IncompatibleVersion for a zeroed version header"),
            }
        }

        round_trip(HMAC_SM3::new(&key).unwrap(), &key, msg);
    }

    /// Exercises the `keygen_from_rng()` function of each HMAC type alias:
    ///   * the generated key must not be the all-zero array,
    ///   * `keygen_from_rng()` returns a ready-to-use `KeyType::MACKey` key, so that
    ///   * `HMAC::new(&key)` accepts the freshly generated key, without error.
    ///
    macro_rules! keygen_test {
        ($test_name:ident, $hmac:ident, $n:literal) => {
            #[test]
            fn $test_name() {
                let mut rng = HashDRBG_SHA512::new_from_os();
                let key = $hmac::keygen_from_rng(&mut rng).expect("keygen_from_rng should succeed");

                assert_eq!(key.key_len(), $n, "key should be the hash's output length");
                assert_eq!(key.key_type(), KeyType::MACKey, "keygen should return a MAC key");
                assert!(
                    key.ref_to_bytes().iter().any(|&b| b != 0),
                    "keygen produced an all-zero key"
                );

                $hmac::new(&key).expect("HMAC::new should accept a freshly generated key");
            }
        };
    }

    keygen_test!(keygen_hmac_sm3, HMAC_SM3, 32);
}
