use std::io::{self, Read};
use std::process::exit;

use bouncycastle::ascon::ascon_aead128::{
    AsconAead128, AsconAead128Decryptor, AsconAead128Encryptor,
};
use bouncycastle::ascon::ascon_cxof128::AsconCXof128;
use bouncycastle::ascon::ascon_hash256::AsconHash256;
use bouncycastle::ascon::ascon_xof128::AsconXof128;
use bouncycastle::core::errors::SymmetricCipherError;
use bouncycastle::core::key_material::{
    KeyMaterial, KeyMaterialTrait, KeyType, do_hazardous_operations,
};
use bouncycastle::core::traits::{
    AEADCipherDecryptor, AEADCipherEncryptor, SecurityStrength, SymmetricCipherDecryptor,
    SymmetricCipherEncryptor,
};
use bouncycastle::hex;

use crate::helpers;

/// Load a hex string or a binary/hex file into bytes; exits with an error if neither is supplied.
fn load_bytes(value: &Option<String>, value_file: &Option<String>, label: &str) -> Vec<u8> {
    if let Some(file) = value_file {
        helpers::read_from_file(file)
    } else if let Some(v) = value {
        hex::decode(v).unwrap_or_else(|_| {
            eprintln!("Error: {label} is not valid hex.");
            exit(-1)
        })
    } else {
        eprintln!("Error: {label} must be supplied.");
        exit(-1)
    }
}

fn load_optional_bytes(
    value: &Option<String>,
    value_file: &Option<String>,
    label: &str,
) -> Option<Vec<u8>> {
    if let Some(file) = value_file {
        Some(helpers::read_from_file(file))
    } else {
        value.as_ref().map(|v| {
            hex::decode(v).unwrap_or_else(|_| {
                eprintln!("Error: {label} is not valid hex.");
                exit(-1)
            })
        })
    }
}

fn require_16(bytes: Vec<u8>, label: &str) -> [u8; 16] {
    bytes.try_into().unwrap_or_else(|_: Vec<u8>| {
        eprintln!("Error: {label} must be exactly 16 bytes.");
        exit(-1)
    })
}

/// Build a `KeyMaterial<16>` for the AEAD key, warning (and forcing usable metadata) only if the
/// key turns out to be low-entropy (e.g. all-zero), the same way `helpers::parse_seed` does.
fn load_key_material(key_bytes: &[u8; 16]) -> KeyMaterial<16> {
    let mut key =
        KeyMaterial::<16>::from_bytes_as_type(key_bytes, KeyType::SymmetricCipherKey).unwrap();
    if key.key_type() == KeyType::Zeroized || key.security_strength() < SecurityStrength::_128bit {
        eprintln!(
            "Warning: low entropy key provided. We'll still process it, but it may be insecure."
        );
        do_hazardous_operations(&mut key, |k| {
            k.set_key_type(KeyType::SymmetricCipherKey)?;
            k.set_security_strength(SecurityStrength::_128bit)
        })
        .unwrap();
    }
    key
}

/// Ascon-Hash256 of stdin. Streaming update; 256-bit digest.
pub(crate) fn hash256_cmd(output_hex: bool) {
    helpers::stream_hash(AsconHash256::new(), output_hex);
}

/// Ascon-XOF128 of stdin, producing `output_len` bytes. Streaming absorb.
pub(crate) fn xof128_cmd(output_len: usize, output_hex: bool) {
    helpers::stream_xof(AsconXof128::new(), output_len, output_hex);
}

/// Ascon-CXOF128 of stdin with a hex customization string, producing `output_len` bytes.
pub(crate) fn cxof128_cmd(customization: &Option<String>, output_len: usize, output_hex: bool) {
    let z = match customization {
        Some(v) => hex::decode(v).unwrap_or_else(|_| {
            eprintln!("Error: customization is not valid hex.");
            exit(-1)
        }),
        None => Vec::new(),
    };
    let x = AsconCXof128::with_customization(&z).unwrap_or_else(|_| {
        eprintln!("Error: customization string exceeds 256 bytes.");
        exit(-1)
    });
    helpers::stream_xof(x, output_len, output_hex);
}

/// Ascon-AEAD128 of stdin. Encrypts (stdin = plaintext, output = nonce||ciphertext||tag) or, with
/// `decrypt`, decrypts (stdin = nonce||ciphertext||tag, output = plaintext). Decryption exits with
/// a non-zero status if the authentication tag does not verify.
///
/// The 16-byte nonce is generated by the library and travels at the head of the stream, the same
/// convention `block_mode_cmd`/`stream_mode_cmd` use for their IV, so an encrypt and a decrypt
/// compose in a pipeline with nothing but the key passed between them. A caller-supplied `nonce`
/// overrides that and is kept out of the stream in both directions; it is there for known-answer
/// vectors, and repeating one under a given key breaks Ascon-AEAD128 outright.
///
/// Both directions stream stdin in fixed-size chunks (no full-buffer slurp). Encryption emits
/// ciphertext eagerly, before the tag is known; note that in the decryption direction, plaintext
/// is likewise emitted before the tag has been checked, so it should not be treated as
/// authentic until this command exits with status 0 (see the crate's "Security Considerations").
pub(crate) fn aead128_cmd(
    key: &Option<String>,
    key_file: &Option<String>,
    nonce: &Option<String>,
    nonce_file: &Option<String>,
    ad: &Option<String>,
    decrypt: bool,
    output_hex: bool,
) {
    let key = load_key_material(&require_16(load_bytes(key, key_file, "key"), "key"));
    let nonce =
        load_optional_bytes(nonce, nonce_file, "nonce").map(|bytes| require_16(bytes, "nonce"));
    let ad_bytes = match ad {
        Some(v) => hex::decode(v).unwrap_or_else(|_| {
            eprintln!("Error: associated data is not valid hex.");
            exit(-1)
        }),
        None => Vec::new(),
    };
    let ad_opt = if ad_bytes.is_empty() { None } else { Some(ad_bytes.as_slice()) };

    if decrypt {
        aead128_decrypt_stream(&key, nonce.as_ref(), ad_opt, output_hex);
    } else {
        aead128_encrypt_stream(&key, nonce.as_ref(), ad_opt, output_hex);
    }
}

/// Generated-nonce encryption: drives [`AsconAead128Encryptor`] in the inline `ciphertext || tag`
/// layout (the inherited [`SymmetricCipherEncryptor::do_final_out`]), writing the nonce it
/// generated ahead of the stream.
/// With an explicit nonce there is no nonce to write, so that case goes to
/// [`aead128_encrypt_stream_with_explicit_nonce`] instead.
fn aead128_encrypt_stream(
    key: &KeyMaterial<16>,
    nonce: Option<&[u8; 16]>,
    ad_opt: Option<&[u8]>,
    output_hex: bool,
) {
    if let Some(nonce) = nonce {
        aead128_encrypt_stream_with_explicit_nonce(key, nonce, ad_opt, output_hex);
        return;
    }

    let (mut cipher, nonce) = AsconAead128Encryptor::do_encrypt_init(key).unwrap_or_else(|e| {
        eprintln!("Error: couldn't start encryption: {e:?}");
        exit(-1);
    });
    if let Some(ad) = ad_opt {
        // infallible: `do_update_aad` only refuses AAD once plaintext has been fed in, and none
        // has been yet.
        cipher.do_update_aad(ad).unwrap();
    }

    helpers::write_bytes_or_hex(&nonce, output_hex);

    let mut buf = [0u8; 1024];
    loop {
        let n = io::stdin().read(&mut buf).expect("Failed to read from stdin");
        if n == 0 {
            break;
        }
        let mut out = [0u8; 1024];
        // infallible: `out` is as long as `buf`, so it cannot be shorter than the `n` bytes read
        // into it, which is the only length `OutputBufferTooSmall` could complain about.
        let written = cipher.do_update_out(&buf[..n], &mut out).unwrap();
        helpers::write_bytes_or_hex(&out[..written], output_hex);
    }
    // infallible: Ascon-AEAD128 holds nothing back, so the inline final is only the 16-byte tag.
    let mut tail = [0u8; 16];
    let tail_len = cipher.do_final_out(&mut tail).unwrap();
    helpers::write_bytes_or_hex(&tail[..tail_len], output_hex);
    if output_hex {
        println!();
    }
}

/// Encryption under a caller-supplied nonce, which nothing is written to the stream for. This
/// drives the inherent [`AsconAead128`] API rather than the `AEADCipherEncryptor` pair because the
/// pair generates its own nonce by construction -- `do_encrypt_init` owns that choice, which is
/// the point of the trait -- and has no caller-supplied-nonce constructor to call here.
fn aead128_encrypt_stream_with_explicit_nonce(
    key: &KeyMaterial<16>,
    nonce: &[u8; 16],
    ad_opt: Option<&[u8]>,
    output_hex: bool,
) {
    let mut cipher = AsconAead128::new_encrypting(key, nonce, ad_opt).unwrap_or_else(|e| {
        eprintln!("Error: couldn't start encryption: {e:?}");
        exit(-1);
    });
    let mut buf = [0u8; 1024];
    loop {
        let n = io::stdin().read(&mut buf).expect("Failed to read from stdin");
        if n == 0 {
            break;
        }
        cipher.do_encrypt_update(&mut buf[..n]);
        helpers::write_bytes_or_hex(&buf[..n], output_hex);
    }
    let tag = cipher.do_encrypt_final();
    helpers::write_bytes_or_hex(&tag, output_hex);
    if output_hex {
        println!();
    }
}

/// Decrypts a stream whose final 16 bytes are the tag, which is only known once EOF is reached.
/// [`AsconAead128Decryptor`] holds the last 16 bytes it has seen back itself, releasing everything
/// before them as soon as it is known not to be part of the tag; at EOF
/// [`SymmetricCipherDecryptor::do_final`] checks what it held back as the tag.
fn aead128_decrypt_stream(
    key: &KeyMaterial<16>,
    nonce: Option<&[u8; 16]>,
    ad_opt: Option<&[u8]>,
    output_hex: bool,
) {
    const CHUNK: usize = 1024;
    let nonce = match nonce {
        Some(nonce) => *nonce,
        None => {
            let mut nonce = [0u8; 16];
            if let Err(e) = io::stdin().read_exact(&mut nonce) {
                if e.kind() == io::ErrorKind::UnexpectedEof {
                    eprintln!("Error: ciphertext is shorter than the 16-byte nonce.");
                    exit(-1);
                }
                panic!("Failed to read from stdin: {e}");
            }
            nonce
        }
    };

    let mut cipher = AsconAead128Decryptor::do_decrypt_init(key, &nonce).unwrap_or_else(|e| {
        eprintln!("Error: couldn't start decryption: {e:?}");
        exit(-1);
    });
    if let Some(ad) = ad_opt {
        // infallible: as on the encrypt side, no ciphertext has been fed in yet.
        cipher.do_update_aad(ad).unwrap();
    }

    let mut buf = [0u8; CHUNK];
    let mut out = [0u8; CHUNK];
    loop {
        let n = io::stdin().read(&mut buf).expect("Failed to read from stdin");
        if n == 0 {
            break;
        }
        // infallible: the decryptor releases at most what it has held back (16 bytes) plus what
        // it is given, less the 16 it keeps, so never more than the `n <= CHUNK` bytes read.
        let written = cipher.do_update_out(&buf[..n], &mut out).unwrap();
        helpers::write_bytes_or_hex(&out[..written], output_hex);
    }

    match cipher.do_final() {
        Ok((last, last_len)) => {
            helpers::write_bytes_or_hex(&last[..last_len], output_hex);
            if output_hex {
                println!();
            }
        }
        Err(SymmetricCipherError::DecryptionFailed) => {
            eprintln!("Error: ciphertext is shorter than the 16-byte tag.");
            exit(-1);
        }
        Err(_) => {
            eprintln!("Error: Ascon-AEAD128 authentication failed.");
            exit(-1);
        }
    }
}
